### ISSUE TITLE
About Covid-Warn App

### ISSUE THREAD

**Issue by Rika28** [corona-warn-app/cwa-app-ios#1098]
Hi,

I have a question about the Covid Warn App. I saw that there is one Match count, however, in the app it shows No risk encounters. I want to know why is that? Does one match count mean that I have one encounter? 

![WechatIMG507](https://user-images.githubusercontent.com/70505144/91689277-0e749600-eb64-11ea-9e8d-4dad83ce6db1.jpeg)
![WechatIMG509](https://user-images.githubusercontent.com/70505144/91689280-10d6f000-eb64-11ea-8ae0-bb6f89ca5f92.jpeg)

Thank you!

**Comment by thomasaugsten** [comment]
This exposure check was on 28.08.20 this means you had 3 day ago an exposure with a low risk.
I see you have also a incorrect day counter your are using v 1.2.1 of the CWA?

**Comment by Rika28** [comment]
@thomasaugsten Thank you for your reply. Yes I am using the 1.2.1 of the CWA. Why doesn't it show "one exposure" on the app? How can I know whether it is a low risk or a high risk?

**Comment by thomasaugsten** [comment]
Because it was shown this at the 28.08. Two days later the Random Code collected by iOS is deleted because it is deleted after 14days. This means also the exposure is removed.
With a high risk you got a push notification and if its deleted after 2days it also very likely a low risk because the exposure was long time ago.

**Comment by haosap** [comment]
Hi @Rika28 ,
Thanks for your report. While you're using or since you have downloaded the App, have you ever activate or deactivate the "Risiko-Ermittlung"? Or see your iPhone to Flight mode daily? cc @ChristianKienle 
Thanks.

**Comment by Rika28** [comment]
@thomasaugsten do you mean that, I met a positive person 10 days ago, and he was diagnosed on 28.08, so that the data was deleted now? So it doesn't mean that I met him/her on 28.08. Did I understand you correctly? If not, how could the data be deleted only after 3 days.

**Comment by Rika28** [comment]
@haosap hi, I never deactivate the Risiko-Ermittlung. And I really want to know what's going on exactly. Thanks!

**Comment by haosap** [comment]
Hi @Rika28,
Thanks. good to know that. Could you please also export your exposure file and share it here?

**Comment by Rika28** [comment]
@haosap I export all of them here. Only one match count is on the 28.8. Could you have a look?
<img width="607" alt="1" src="https://user-images.githubusercontent.com/70505144/91700708-92d01480-eb76-11ea-9d83-e42483fd86ae.png">

<img width="608" alt="2" src="https://user-images.githubusercontent.com/70505144/91700707-919ee780-eb76-11ea-9855-50d23627a798.png">

<img width="590" alt="8" src="https://user-images.githubusercontent.com/70505144/91700669-8b107000-eb76-11ea-9b6e-e08e38aeb9f1.png">
<img width="593" alt="7" src="https://user-images.githubusercontent.com/70505144/91700678-8c419d00-eb76-11ea-9d0f-2cf5cbc4e092.png">
<img width="590" alt="6" src="https://user-images.githubusercontent.com/70505144/91700686-8d72ca00-eb76-11ea-9558-ec8b3c825ee3.png">
<img width="586" alt="5" src="https://user-images.githubusercontent.com/70505144/91700688-8ea3f700-eb76-11ea-9747-48ae85e6b0d3.png">
<img width="601" alt="4" src="https://user-images.githubusercontent.com/70505144/91700693-8fd52400-eb76-11ea-8f0a-b82a32308901.png">
<img width="595" alt="3" src="https://user-images.githubusercontent.com/70505144/91700698-906dba80-eb76-11ea-9f51-9f796b8526eb.png">

**Comment by thomasaugsten** [comment]
It would be easier with the file but as I see at the moment my guess is. You had exposure on 14.08.20 then your phone saved a random id from the exposure. The person get his positive test result on 27.08.20 and submitted his diagnoses key you received this diagnoses keys on 28.08 and the ENF had a MatchCount of 1. This was also visible on the 28.08 in the app.
Because of the long time between your exposure and the positive test result of the exposure the risk is very low because the person not infectious at this time.  At the 29.08 the random id was 14 days old on your phone and your phone deleted this random id this lead to a matchCound of 0 because the match was deleted.

**Comment by Rika28** [comment]
@thomasaugsten That makes sense. Thank you so much for your explanation!

**Comment by Ein-Tim** [comment]
@Rika28 
So when you happy withe the answer could you close this Issue? 
Thanks!
