### ISSUE TITLE
Faulty risk reporting after factory reset and restoring phone from backup

### ISSUE THREAD

**Issue by christqoh** [corona-warn-app/cwa-app-ios#1379]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Had to reset my iPhone a few days back. Backed it up to Mac, did factory reset and reinstalled from Backup.
Exposure Logs were gone (as expected; https://www.coronawarn.app/en/faq/#backup) but Corona Warn still reports "Risikoermittlung dauerhaft aktiv" (different from https://www.coronawarn.app/en/faq/#migration_Apple)

## Expected behaviour

Report risk with respect to the actual number of log files available.
Note that I only noticed this behavior today, the reset was three days ago (compare screenshots below). However, the app has been reporting "Risikoermittlung dauerhaft aktiv" throughout. 

## Steps to reproduce the issue

Back up phone with 14 days of exposure logs to Mac (macOS 10.15.7). 
Factory-reset the phone from the Settings App ("Erase All Content and Settings"). 
Restore from Backup. 

## Technical details

- iOS Version: 14.0.1
- Device: iPhone 11 Pro

![IMG_8C227AD21CCB-1](https://user-images.githubusercontent.com/34374252/96695717-3de89780-138a-11eb-9f37-a6742bb58e7c.jpeg)

![IMG_3FC8C83F827C-1](https://user-images.githubusercontent.com/34374252/96695725-40e38800-138a-11eb-8f2d-d1d8920263fa.jpeg)

---
Internal Tracking ID: EXPOSUREAPP-3406

**Comment by thomasaugsten** [comment]
We have no access on how many TEKs are available at the moment we only can count the days how long the app was active. This state is in the backup and also restored.

**Comment by christqoh** [comment]
I see, makes sense. I feel like this could communicate an unjustified sense of trust though. On the long run Apple should give you access to  the number of TEKs on the phone; until then: Since it is known that the log files are not backed up themselves, is there a way to exclude the information how many days the app was active from the backup? This would then reset the counter of days when restoring from backup...

**Comment by heinezen** [comment]
Hello @christqoh ,

Thank you for the report. We have created a ticket in the internal Jira for your issue (ticket ID: EXPOSUREAPP-3406). The developers will now investigate it and try to find a solution. Any updates or fixes will be communicated here on Github in this issue thread.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Any updates here?

**Comment by dsarkar** [comment]
@Ein-Tim @christqoh 

As T. Augsten already stated, there is not much the dev team can do about this. It is an Apple issue, how backups are handled.

**Comment by Ein-Tim** [comment]
Okay thanks @dsarkar, so I propose to close this if there are no other reports of this Issue (or you asked Apple and they are processing the request).

**Comment by Ein-Tim** [comment]
I ran into the same issue after restoring an iPhone 6s from an iCloud Backup, this is very confusing. 

Maybe this could be reopened as an Enhancement request, or should I open a new (Wishlist) issue for this?

**Comment by dsarkar** [comment]
@Ein-Tim There are currently internal discussions on how to change the information of active days on the card: It might be dropped and/or replaced by another message (e.g. days since installation). There are several reasons to do so, just to mention some:

- This issue here e.g.: can't be fixed by dev team, since this is an Apple issue how backups are handled
- We have also the issue being stucked at 13/14 days on some iOS devices
- How shall period of times with BT off, phone off, wifi/data off be handled ?
- Android phones e.g. it is apparently not trivial to figure out BT off time.
- the grey card actually was dropped in the meantime.

So altogether, with all these issues it is actually not very clear, what " n/14 active days" means exactly and there are (too) many ways how one could possibly define and interpret this number, leading amongst some users apparently more to confusion than adding additional useful information. So, we might expect to see some changes here anyway in one of the future releases.

However, of course, feel free to create another wishlist item.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thank you so much for this update! 

I won't create another item, since this seems to be unnecessary if they are already in discussion internally. 

Thanks again! ❤️

**Comment by daimpi** [comment]
@dsarkar thanks for the heads-up. I've [mirrored](https://github.com/corona-warn-app/cwa-wishlist/issues/102#issuecomment-784139388) your comment to the wishlist issue which discusses this topic, to also let ppl there know about the teams considerations 🙂.
