### ISSUE TITLE
Risk encounters per Person per day (positive keys)

### ISSUE THREAD

**Issue by jonnyfux** [corona-warn-app/cwa-app-ios#1456]
* [ X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ X] Question has not already been asked in another issue

## Your Question
If I understand correctly, if a person uploads a positive test result, the last 14 keys are uploaded. My App then checks whether we exchanged IDs derived from those keys and warns me if we met. **My question is now, if I was in contact with a later tested person for the last 14 days and no other contact at all, I will still get 14 risk encounters? So one per day?** 

If that be the case, I find that very confusing. It would be better to get "you had 14 high risk encounters with 1 person". So if you know that all your encounters were with mask in a well ventialted room you would not have to worry and have to stress the test capacities with unnecessary tests.

**Comment by Ein-Tim** [comment]
> My question is now, if I was in contact with a later tested person for the last 14 days and no other contact at all, I will still get 14 risk encounters? So one per day?

Yes, that is correct.

**Comment by daimpi** [comment]
Hi @jonnyfux & @Ein-Tim,
> >  My question is now, if I was in contact with a later tested person for the last 14 days and no other contact at all, I will still get 14 risk encounters? So one per day?
>
> Correct.

Yes this is in principle correct even though in practice there can be a maximum of 13 encounters caused by one user. See [here](https://github.com/corona-warn-app/cwa-server/issues/723#issuecomment-684812642) or [here](https://github.com/corona-warn-app/cwa-app-android/issues/1302#issuecomment-703275964) for the reasons behind this: bascially there are two different mechanisms (1. DK retention policy on the server and 2. RPI retention on the device) which each on their own make it so that you can get a maximum of 13 matches from one one person with the current implementation. See also this explanation how RPIs map to encounters in CWA / matches in your EN log: https://github.com/corona-warn-app/cwa-app-ios/issues/1096#issuecomment-688235743

Regarding 
> If that be the case, I find that very confusing. It would be better to get "you had 14 high risk encounters with 1 person".

This is not possible for a good reason: Temporary Exposure Keys (TEKs) - sometimes also referred to as diagnosis keys (DKs) - change every day at 00:00 UTC. This is done in order to preserve privacy by making it harder to generate movement profiles of ppl who upload their keys.

**Comment by jonnyfux** [comment]
Hey @Ein-Tim @daimpi, 

Thanks for the clarifications!
