### ISSUE TITLE
[Discussion][Solved] How a red alert turns into green alert.

### ISSUE THREAD

**Issue by TeRe20200** [corona-warn-app/cwa-app-ios#1675]
Hi everyone, I am writing on behalf of a friend of mine who encountered the following issue:

She had a red encounter pushed on her app on Monday, 7th of December, after a colleague of hers was diagnosed with Covid. (Said colleague had first symptoms on saturday, 28th, got tested a week after and got her results on monday 7th). My friend saw that colleague for the last time on friday, the 27th.  
The Monday (7th of Dec.) alert my friend got was the following: 

![grafik](https://user-images.githubusercontent.com/67905190/101951021-9142cd80-3bf6-11eb-8b79-da7bc8299885.png)

Today my friend got pushed another 2 encounters, which was very irritating, as no one else at work (and my friend strictly goes to work and then straight home) was diagnosed with Covid around her. The alert looked like this: 

![grafik](https://user-images.githubusercontent.com/67905190/101951059-a4ee3400-3bf6-11eb-976f-905a1c5b79e8.png)

My friend knew that today at 8:30 pm her very first encounter would be erased from her log (as 14 days had passed) and as she checked per app, all the red logs were gone and she had two low risk encounters on her app:

![grafik](https://user-images.githubusercontent.com/67905190/101951082-b0d9f600-3bf6-11eb-880a-6e838e7e0dce.png)

This seems to be a very big bug, showing 2 low risk encounters as high risk encounters? How is this even possible?

**Comment by Ein-Tim** [comment]
Hey @TeRe20200 

Thanks for reporting!

Please not that "Days since Encounter" in the High Risk Card are not correct:
https://github.com/corona-warn-app/cwa-documentation/issues/422
The days shown there are the days since any encounter, also from Low-Risk ones.

Also if you have a High Risk Encounter than there is the Quoute: "n Risiko Begegnungen", but there also Low Risk Encounters are included: https://github.com/corona-warn-app/cwa-wishlist/issues/233.


Still I would love to take a deeper look into this, could you maybe ask your friend to export her EN-Log here?
She should also tell us her CWA Version and the iOS Version.

<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it form .json to .txt**
</details>

Thanks and have a nice evening!

**Comment by TeRe20200** [comment]
@Ein-Tim thank you so much for your quick reply and your very well written explanation. 

As a matter of fact my friend was next to the colleague the whole week from monday, 23rd to friday, 27th. The colleague felt sick on saturday (28th), stayed home from then on and got her testresult more than 8 days later, on monday the 7th.
**Just out of pure curiosity**: What would the app have shown on monday the 7th receiving the red encounter? Just ONE red encounter with the information "10 days since last exposure" (as in friday)?

I am very curious what you will find out "what happened" , find it attached here. Thank you, once again, for spending your time on this issue.

[Exposure.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5681773/Exposure.txt)

**Comment by Ein-Tim** [comment]
> Just out of pure curiosity: What would the app have shown on monday the 7th receiving the red encounter? Just ONE red encounter with the information "10 days since last exposure" (as in friday)?

Yes this is what should be shown...

---

I am looking into this right now, but this will take some time. I will report back here ASAP.

**Comment by Ein-Tim** [comment]
Okay, I can share a detailed analysis if you like to tomorrow, but I can definetly say that the 2 encounters which are shown to your friend now are not the same encounters from the beginning. Everything is working correctly. @TeRe20200

**Comment by TeRe20200** [comment]
@Ein-Tim Please forgive me if I am asking stupid questions here, I just want to understand the following:
My friends colleague gets the positive result on the 7th and logs it in. In the past 14 days (counting from the 7th on) my friend saw said colleague on the 24th, 25th, 26th and 27th. Why doesn't the coronaapp log every daily encounter with her colleague as a new "Begegnung"? Because then it would have made sense that she got an alert that said "4 encounters, the last one 10 days ago". Didn't I read somewhere that the same person can give you more than one "encounter alerts"?

And I find it very confusing, that once you get a red alert the green alerts ones can rise the number of encounters shown in red, because to my friend (and me) it looked like she had 3 red alerts, as we didn't know the number was including green alerts. This is very misleading to be honest....

**Comment by Ein-Tim** [comment]
@TeRe20200 

> Why doesn't the coronaapp log every daily encounter with her colleague as a new "Begegnung"? 

It should have done this. 
TBH I've asked myself the same question. If your friend was in close contact with the colleague, the App should min. have showed 4 encounters. 
It **could** be that the ENF (the underlying API from Google/Apple) _missed_ one contact day, _decided_ that the other two contact days as low risk and only one as high risk. 
Now the question is: Why did the ENF decide like this? 
This question nobody can really answer... 

> Didn't I read somewhere that the same person can give you more than one "encounter alerts"?

Yes this is correct, see:

https://www.coronawarn.app/en/faq/#count_per_day

> And I find it very confusing, that once you get a red alert the green alerts ones can rise the number of encounters shown in red, because to my friend (and me) it looked like she had 3 red alerts, as we didn't know the number was including green alerts. This is very misleading to be honest....

Yeah I know... 
There is a open Issue in the Wishlist Repo about this: 2. punkt: https://github.com/corona-warn-app/cwa-wishlist/issues/233

But at least we will see an improvement reg. the days with the next release, 1.8.0. There the exact date will be shown and also this will be the day of the last risky (red) encounter, and not the date of any encounter.

**Comment by Ein-Tim** [comment]
So, here's what I found in the EN-Log:

<table>
<tr> 
	<td> Hash 
	<td> Time
	<td> Matches
	<td> Meaning
<tr>
	<td> 93E9F0A2427C5EE94F8E48CCC41C45750742F88C6354A17EF94E4D5D12EF291F
	<td> 2020-12-07 20:27:49
	<td> 3
	<td> Hourly file, reporting 3 Encounters 
<tr>
	<td> 1A9ED80561685CEC9DB933243156323CC2459659BEB46189B34A73D5A6480116
	<td> 2020-12-09 14:35:45
	<td> 3
	<td> Daily file reporting 3 encounters, which were already reported on the day before by the hourly file. 
<tr>
	<td> 1A9ED80561685CEC9DB933243156323CC2459659BEB46189B34A73D5A6480116
	<td> 2020-12-10 07:15:08
	<td> 2
	<td> One Encounter drops out of the hash (older then 14 days)
<tr>
	<td> 1A9ED80561685CEC9DB933243156323CC2459659BEB46189B34A73D5A6480116
	<td> 2020-12-10 23:23:20 +0100
	<td> 1
	<td> Another encounter drops out of the hash (older then 14 days)

<tr> 
	<td> 959FB0F3BA33AD3863866FC13CA028B48C14F2A9756EE619AC0DBFB7B7E4BFDC 
	<td> 2020-12-11 08:20:47 +0100
	<td> 1
	<td> A new encounter comes in via a hourly file

<tr>
	<td> 10C19780EFADAB65554100F3A6ACA0C9552B0E9784538AA70303F639D36EFE4A
	<td> 2020-12-11 16:29:09 +0100
	<td> 1
	<td> Another new encounter comes in via a hourly file

<tr>
	<td> 1A9ED80561685CEC9DB933243156323CC2459659BEB46189B34A73D5A6480116
	<td> 2020-12-11 20:32:10 +0100
	<td> 0
	<td> The last known encounter from the beginning drops out of the 14 days window

</table>

---

I hope this table helps you to understand. `1A9ED80561685CEC9DB933243156323CC2459659BEB46189B34A73D5A6480116` is the hash from the beginning (3 Matches). As you can see all of the encounters drop out of the 14 windows... The encounters shown now are all new. Please note that this table is only showing the relevant changes.

---

So as you can see, everything is working correctly here. If you are happy with the answer, please close this Issue.

**Comment by ndegendogo** [comment]
@TeRe20200 I have just looked at the exposure log file you posted.
*Just a hint how to read it - the newest entries are shown at the top, so if you want to read it in chronological order, then you start at the bottom).*

On 27 Nov 19:37 we see 1 match. Note that 19:37 is timestamp of the check, **not** of the encounter (just to avoid any misunderstanding). From the log file we cannot tell if red or green (but as you have not reported any red warning on that day, we assume this is green). It is contained in an hourly file with hash=40CC.. and 1449 keys in total.
Next day and all the following days we see the same match, now in a daily file (hash=8756..., with 20078 keys). We see it on 07 Dec 04:19 the last time. At 08:21 it is gone.
Now comes the interesting part. Same day 07 Dec at 20:27 we see 3 matches in an hourly file (hash=93E9.., key count=955). From your report this is the red warning. The app counts every day separately, and cannot distinguish if it is the same person or a different. However, I assume that all three are related to this collegue, and maybe all three red. The latest (most recent) 10 days ago, as shown on your screenshot.
Why not 4? I think the 4th was already 14 days old and therefore not shown.
Next day these three appear in a daily file (hash=1A9E.., key count=14913), then start to drop out in the evenings. On 10 Dec evening only one is left.
On 11 Dec 08:20 a new match appears, then at 12:24 another. So total number is 3 now, as shown on your second screenshot. Overall risk score is still red.
In the evening the last red fades out (14 days old), and now we know that the other two are green, because the total risk score is green now.

@Ein-Tim you were faster than me to answer 😊

**Comment by dsarkar** [comment]
Dear  @TeRe20200, @ndegendogo, @Ein-Tim, and community

@TeRe20200, thank you for posting your question here. @ndegendogo and @Ein-Tim did a great job analyzing it. We think this issue is solved now, however, we would suggest not to close this nice example for future reference and better visibility.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
With the hourly files there is so much more transparency what is going on. With daily files only this level of detail would just not be possible. 
**I appreciate this a lot.**

**Comment by TeRe20200** [comment]
@Ein-Tim & @ndegendogo
Thank you A LOT for helping me and my friend to understand the issue - thank you for your quick answers and your time.

**Comment by heinezen** [comment]
Since the questions here were all answered and the information in the thread becomes more and more outdated, I will close this issue.

Thank you everyone for participating

----
Corona-Warn-App Open Source Team
