### ISSUE TITLE
Error 13 after upgrading to CWA 1.9.1 and opening the app

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1715]
Error 13 after upgrading to CWA 1.9.1 and opening the app
---

See this FAQ entry: 
- English https://www.coronawarn.app/en/faq/#ENError13
- German https://www.coronawarn.app/de/faq/#ENError13 

If you updated to Corona-Warn-App version 1.9.1., some users may receive the following error message:

- German error message: "Fehler 13: Ihre Risiko-Ermittlung für den heutigen Tag wurde bereits durchgeführt. Bitte versuchen Sie es in 24 Stunden erneut."

- English error message: "Error 13: Your exposure logging for today has already been carried out. Please try again in 24 hours."

The Corona-Warn-App is functioning correctly despite this message. If you have any other problems in this context, you can describe your issue in detail in this thread.

Corona-Warn-App Open Source Team

---
ORIGINAL POST BY THE AUTHOR
---

Hi
I upgraded yesterday. Today, in the morning I opened the app, and an error message up, that made little sense, 
the check was done correctly, though.
The screenshot is attached
regards
Uwe Brauer

![error-cwa-1 91](https://user-images.githubusercontent.com/5957203/102591276-0e4bd680-4112-11eb-8185-75ab00d49002.png)

---
Internal Tracking ID: [EXPOSUREAPP-4066](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4066)
Internal Tracking ID: [EXPOSUREAPP-4145](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4145)

**Comment by Ein-Tim** [comment]
@ouboub 
Did you use 1.7.1 before the update?

**Comment by dsarkar** [comment]
Hi @ouboub,

Thanks for reporting. According to the developers, this can happen after the 


If you open the app for the first time after the update, a risk check is initiated immediately, regardless of whether or not a check has already been carried out. This means that in some cases users may receive this error message.
Reference: [EXPOSUREAPP-4066](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4066)

**Comment by ouboub** [comment]
> Hi @ouboub,
> 
> Thanks for reporting. However, you can ignore this message.
> 
> If you open the app for the first time after the update, a risk check is initiated immediately, regardless of whether or not a check has already been carried out. This means that in some cases users may receive this error message.
> 
> Reference: [EXPOSUREAPP-4066](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4066)
> 
> Best wishes, DS
> 
> Corona-Warn-App Open Source Team

Yes I thought, I could ignore it, but I also thought it is worth letting you know, because it might confuse other users

**Comment by ouboub** [comment]
> @ouboub
> Did you use 1.7.1 before the update?

I am pretty sure the answer is yes, but how I can I check it to be completely sure?

**Comment by dsarkar** [comment]
Thanks, we will update the FAQ now.

**Comment by Ein-Tim** [comment]
@ouboub 

> I am pretty sure the answer is yes, but how I can I check it to be completely sure?

You can't... But since @dsarkar stated that this does not mean anything, it's not relevant anymore

**Comment by ouboub** [comment]
> Thanks, we will update the FAQ https://www.coronawarn.app/de/faq/#ENError13 now.
> And yes, we are very happy about any feedback. It tells us also, that we need to communicate more clearly and in a more timely manner.
> 
> Corona-Warn-App Open Source Team

thanks, but it also clearly shows, that it would be better to have more beta testers. Im telling you this also because I am beta tester in various Apple Apps.

**Comment by ellenkoenig** [comment]
I have a somewhat different behavior than the initial reporter. I get the same error, but the check doesn’t happen. So my risk status is „unknown“. I have not opened the app in a few days prior to upgrading. 
![1ECE6C7A-754E-410E-94B5-D4D8F69C81C5](https://user-images.githubusercontent.com/1550201/102721846-a6f27a00-42fd-11eb-93c5-01dbd5312d0a.jpeg)
![2CA68E63-F428-49A8-A125-3A21EF938C2E](https://user-images.githubusercontent.com/1550201/102721850-a954d400-42fd-11eb-94de-a3ce74e77f47.jpeg)
![337C9A99-48B4-4C01-B17D-E93B5F1DE03A](https://user-images.githubusercontent.com/1550201/102721851-a954d400-42fd-11eb-868c-fe9ae47e6c28.jpeg)
![6552AFF7-EB6B-4715-8540-F7142D234EED](https://user-images.githubusercontent.com/1550201/102721853-aa860100-42fd-11eb-9291-74036451fd5a.png)

**Comment by Ein-Tim** [comment]
@ellenkoenig 

Wait, you can't manually start the risk check? What happens when you click the button? Does the error show up again?

**Comment by ellenkoenig** [comment]
@Ein-Tim yes, exactly 
![F3FD2FA8-60F0-46FA-9160-853D61380234](https://user-images.githubusercontent.com/1550201/102722366-f38b8480-4300-11eb-9459-f8a7d0b2c49d.png)

**Comment by Ein-Tim** [comment]
Okay... 
@ellenkoenig 
Did a restart from the App/your phone change something? 

Could you maybe provide your EN-Log here, so that I can see what happens there? 


<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


_This log does not conatin any private information, but the number of encounters._

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it form .json to .txt**
</details>

**Comment by ellenkoenig** [comment]
@Ein-Tim Restarting the app didn’t help. I don’t want to restart my phone right now. 

Here is the log: 
[ExposureChecks-2020-12-20.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5721391/ExposureChecks-2020-12-20.zip)

**Comment by Ein-Tim** [comment]
Okay, thanks for sharing your log.

This is very weird because a check happend today at 19:09 and also one at 15:08. 
But I see the "MatchCount" in your log and this is not normal under 1.9.1. So, could you please make sure that you are really using 1.9.1?

**Comment by ellenkoenig** [comment]
@Ein-Tim I updated a few hours ago to whatever was the most recent version offered. What else could I do?

**Comment by ellenkoenig** [comment]
@Ein-Tim Here is the Update confirmation. 
![802AA6BE-7D6B-4DD4-B3EF-903B992FEAB2](https://user-images.githubusercontent.com/1550201/102723072-e3c26f00-4305-11eb-9ade-211f4f63279a.jpeg)

**Comment by ndegendogo** [comment]
@ellenkoenig ENF error 13 means: the API was called too often - [see here](https://developer.apple.com/documentation/exposurenotification/enerror/code/ratelimited).
I suggest that you wait until tomorrow, and try then again.
Please report if this helped.

**Comment by ellenkoenig** [comment]
@ndegend

> @ellenkoenig ENF error 13 means: the API was called too often - [see here](https://developer.apple.com/documentation/exposurenotification/enerror/code/ratelimited).
> I suggest that you wait until tomorrow, and try then again.
> Please report if this helped.

Sure, that might or might not help. The inconsistent thing about this error is that I didn’t open the app in the 24 hrs before updating. So how could the API be called too often?

**Comment by Ein-Tim** [comment]
@ndegendogo 
Yes she can wait but AFAIK this Error will prevent further calls to the ENF but they are happening here...

**Comment by ndegendogo** [comment]
> how could the API be called too often?

@ellenkoenig **you are absolutely right**
I just checked your uploaded file and it shows 5 checks today - *which is definitely not above any limit*.
Do you remember at which time you upgraded to 1.9.1? Before or after the check at 19:09?

**Comment by ellenkoenig** [comment]
@ndegendogo I would say after the check at 19:09. Probably around 19:30-19:45ish.

**Comment by thomasaugsten** [comment]
After updating to v2 an exposure check will be enforced. The v1 checks will count into v2 this means in rare case it can happens the limit is already reached. Please follow the information and wait 24h.

**Comment by ndegendogo** [comment]
Thanks @thomasaugsten 

*so maybe Apple does not count max 14 checks per day, but calculates the limit with finer granularity ... and throws this error if the last check is less than 2 hours ago ... (just speculating ...)*

**Comment by FallobstAmateur** [comment]
Hello, everybody, 
I’m using iOS 14.3 and CWA 1.10.1 on a iPhone SE 2016. Since yesterday I got always the notification mentioned above. Restarting my iPhone and waiting for 24 hours, as mentioned in the app’s FAQs didn’t help. This is the actual screenshot:   
![B8C18BB2-E504-4CB0-913A-9B0A80646DE6](https://user-images.githubusercontent.com/76879652/103462884-b1af0500-4d28-11eb-8749-839e343e873f.png)

**Comment by ellenkoenig** [comment]
Oh, apologies, I forgot to report back. Waiting 24h did fix the issue for me back then. Now the app is working again as it should.

**Comment by Ein-Tim** [comment]
@FallobstAmateur 
Could you please provide a screenshot from the main screen of Corona-Warn-App without the error message? 

Additionally you could provide your EN-Log here, so we can see if the Exposure Checks are working.

<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


_This log does not conatin any private information, but the number of encounters._

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it form .json to .txt**
</details>

**Comment by FallobstAmateur** [comment]
Hello,

I added the EN-Log as a Word-Document; hopefully it will work for you. It’s
been quite difficult to get this log into this specific mail...

The next screenshot will be sent via GitHub.

Many thanks
Torsten Muth-Huber

Ein_Tim <notifications@github.com> schrieb am Sa. 2. Jan. 2021 um 18:58:

**Comment by FallobstAmateur** [comment]
@Ein-Tim 
Good Evening, 
as promised, here are two new screenshots:
![DBB8A89E-25F5-4D9A-968D-541C299AE7B5](https://user-images.githubusercontent.com/76879652/103464327-05bee700-4d33-11eb-89ad-3d1afb76d79b.png) and after deleting this notification: 
![FEF657D4-8518-4950-AD85-101EED0CB922](https://user-images.githubusercontent.com/76879652/103464348-4454a180-4d33-11eb-83b5-ffb65d5dc045.png)

**Comment by Ein-Tim** [comment]
Okay interesting, thank you for sharing @FallobstAmateur. 

The last successful exposure check was today at 12:17. 
But I can't really tell why this message pops up. Sadly the upload of your log file did not work, could you maybe simply open up your phones settings and then follow these steps: 

 
`Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ 

From the screen you see then you can make a screenshot and upload it here, then I can see when (if) the checks happen... 

When did you update to 1.10.1? 
Did you use 1.9.1 before or did you update from a later version.

**Comment by FallobstAmateur** [comment]
Ein_Tim <notifications@github.com> schrieb am Sa. 2. Jan. 2021 um 19:52:

**Comment by FallobstAmateur** [comment]
Most of my apps are programmed for automatic upgrades.. so this version
should have been installed quite early and is supposed to be based on
version 1.9.1. I’ll try to get more information from my iPhone...

Ein_Tim <notifications@github.com> schrieb am Sa. 2. Jan. 2021 um 19:52:

**Comment by Ein-Tim** [comment]
Thank you @FallobstAmateur.

**Comment by FallobstAmateur** [comment]
Okay, the Update was done on New Year’s Eve, but I can’t guarantee that the
predecessant version was really 1.9.1.  Sorry @Ein-Tim

Ein_Tim <notifications@github.com> schrieb am Sa. 2. Jan. 2021 um 20:04:

**Comment by Ein-Tim** [comment]
Okay no problem @FallobstAmateur.
Sadly, I can't help you any further here. You could wait another 24h and then report back here.

@thomasaugsten maybe you could quickly jump in here?

**Comment by Ein-Tim** [comment]
Hey @FallobstAmateur 

Did anything change, or are you still getting this Pop-Up?

**Comment by FallobstAmateur** [comment]
Hallo @Ein-Tim 
I've restarted the iPhone and wanted to wait until tonight to check once again how the app will react. I'll keep you informed..

**Comment by FallobstAmateur** [comment]
Good Evening to everyone and @Ein-Tim, 
tonight's trial has been successful. The EN-Log shows three Updates today, but the app hasn't shown the error code anymore. 
Thanks for your assistance.

**Comment by dsarkar** [comment]
@FallobstAmateur, Happy to hear, and many thanks for the feedback! 
@Ein-Tim, Thanks !

**Comment by yannikbloscheck** [comment]
Just started to have the same issue with the app version 1.10.1 under iOS 14.3
![CCD1FFFA-733B-4024-B803-A3D963811E35](https://user-images.githubusercontent.com/1571006/104034129-c67c1480-51d0-11eb-8c10-2196586c4710.jpeg)

**Comment by dsarkar** [comment]
@yannikbloscheck Thanks for reporting. Please, wait for at least 24 h. Feedback will be very much appreciated. See https://github.com/corona-warn-app/cwa-app-ios/issues/1715#issue-770687899. Best wishes. DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I don't really understand where this message is coming from, looking at the log from @yannikbloscheck there were only 3 checks in the last 24h, this should only be shown if there were more than 6 checks in the last 24h. 
Are you trying to fix this or is somebody investigating why this is happening? 

cc @thomasaugsten

**Comment by thomasaugsten** [comment]
It is hard to investigate its is very likely that the exposure checks fails but Apple still counting it in the rate limit. I assume their are only a few cases and it is gone after 24hr

**Comment by yannikbloscheck** [comment]
It's now working again. Here is the current [log](https://github.com/corona-warn-app/cwa-app-ios/files/5789073/ExposureChecks-2021-01-08.txt) now after.


From the error code it has to be the rate limit, but like with other errors before (#1000) a big question is why it isn't it just handled better by the app.
Instead this error message pop ups again and again, because the apps tries automatically again. The coloured background for the risk is gone and instead there is a dangerous sounding message "Risiko-Überprüfung fehlgeschlagen". Annoying the user gives him the impression that the app doesn't work while it actually does. In my case the last successful exposure comparison was just four hours ago. So no need for all the communicated drama.
It would be better to stop these error alerts and instead show a message next to the last updated date while keeping the coloured background for the risk and the big risk classification text. I would keep showing the button to manually trigger the exposure comparison in that case and provide an error alert dialog just when the button was used unsuccessfully.

**Comment by ndegendogo** [comment]
@thomasaugsten what exactly is the implemented behaviour in cwa 1.10 when I open the app? In previous versions it triggered a risk check - is this still the same in 1.10? 
Before 1.10 most users did not open the app frequently; but this has (hopefully) changed with the contact diary feature.

**Comment by thomasaugsten** [comment]
It will trigger not at every start. Every 6h if there a new key files downloaded.

**Comment by ThisIsNotALoveSong** [comment]
Hi,
Version 1.10.1 (0)
IOS 14.3

same behaviour as Fallobst described 4 days ago.
I did a lot of refresh in the last 4 hours.
Any clues?
thanks!

**Comment by Ein-Tim** [comment]
Hey @ThisIsNotALoveSong 
Please wait 24h and report back, thanks.

**Comment by dsarkar** [comment]
Hi @ThisIsNotALoveSong. Thanks for reporting. All should be back to normal after 24 h as @Ein-Tim said. In any case we will appreciate your feedback then. Thanks.

**Comment by ThisIsNotALoveSong** [comment]
@dsarkar 
worked early this morning again. Thanks!

not funny: using the app since day 1.
Needed it for the first time waiting for a test result,
so i refreshed the app a lot of times.
Obviously refreshing stresses the app and throws
an userunfriendly error sending me to github.
I told my story and you guys told me to wait for the next refresh 24h
( what i didnt do waiting for the test)
( dont get me wrong, you were very fast and helpful,
I appreciate that)
To emphasise it: you use the refresh a lot of times
When you wait for a test result and then the app goes down?
Giving this error message and error dealing via github?
Cmon - you must be kidding, i am sure 95% of the app users are
not able to get in contact with you via github.

Rest of story:
first my doc, called me to tell me i am positive,
then my healthdepartment called and finally after
4 hours the app went positive.
On my phone no contact to anyone was detected
Within the last weeks.
All my family members didnt get a warning on their mobiles..
Sure the app does what it should?

**Comment by ThisIsNotALoveSong** [comment]
Achja - kacke übrigens, wenn die Kommunikation hier auf Englisch läuft und man
Fehlermeldungskommentare für jedermann hier erfassen lässt...
Oder bin ich hiereinfach falsch?

**Comment by Ein-Tim** [comment]
Hey @ThisIsNotALoveSong 

Just before I answer to your questions, the answer why we are speaking English can you find [here](https://github.com/corona-warn-app/cwa-documentation#working-language).

> Needed it for the first time waiting for a test result,
so i refreshed the app a lot of times.

The ENError 13 alert has absolutely nothing to do with the test result process so even if you clicked "Aktualisieren" inside of the box which showed „Ergebnis liegt noch nicht vor“, this has no impact on Issues like ENError13. 

> I told my story and you guys told me to wait for the next refresh 24h

The In-App pop-up also includes this information. 

> When you wait for a test result and then the app goes down?

As said before, no. The ENError 13 comes from the underlying API, the Exposure Notification Framework, from Apple & Google. It shows up when your risk detection has been checked more than 6 times in 24h. 
Since CWA 1.9.1 there are some rare cases in which this error pops up although there were less than 6 checks in the last 24h. 

> On my phone no contact to anyone was detected
Within the last weeks.
All my family members didnt get a warning on their mobiles..
Sure the app does what it should?

You said you are using the App since one day. If you had „Risiko-Ermittlung“ active the whole time AND there were other phones near your phone, these will be warned (either „Low-Risk encounter“ or „High-Risk encounter“. More detailed information how the warning process works can be found [here](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf)

**Comment by ThisIsNotALoveSong** [comment]
Hey @Ein-Tim,

thanks for your explanations.
ok-so why don‘t you catch the API error and supress the Exception or throw a message for enduser.

Concerning my app install date:
that was a misunderstanding:
I am using the app since the first day available
to download in app store- not just 1 day.
The phones in my house (IOS and Android) were often quite close together-i understand the principles it should work bit obviously it didnt in my case.

**Comment by Ein-Tim** [comment]
@ThisIsNotALoveSong 

> thanks for your explanations.
ok-so why don‘t you catch the API error and supress the Exception or throw a message for enduser.

There are some ENErrors which are not shown to the user, but since the ENError (normally) has a big effect on the risk calculation (next check can be done earliest in 24h) the devs decided to show it. 

> that was a misunderstanding:
I am using the app since the first day available
to download in app store- not just 1 day.

Oh okay I see, I understood you wrong 😅

>The phones in my house (IOS and Android) were often quite close together-i understand the principles it should work bit obviously it didnt in my case.

No phones which were close sho encounters? Not even green ones? 
This is always hard to investigate because of the high data protection of CWA...

**Comment by ThisIsNotALoveSong** [comment]
I understand that you want to show the error, but please keep in mind, normaly this message comes up to a normal user - he doesnt understand anything and is unsure what is happening.
He wants to know he has to wait for 24h but the rest of functionality i working poperly.

What you get from user perspective:
In my case i waited for the test
and got the error message.
To reflect the problem you have to go to github, read your Development and technical advises.
After some reading i understood the problem-but i am sure that you are loosing 98 percent of the users.
And furthermore, they are left unsure if the other application parts are still working.

**Comment by dsarkar** [comment]
@ThisIsNotALoveSong, Thanks for all your detailed input. We will bring forward to the developers your thoughts about showing and interpreting this error message for a "normal" user.

@Ein-Tim Thanks for replying in detail.

**Comment by Ein-Tim** [comment]
@ThisIsNotALoveSong 

> this message comes up to a normal user - he doesnt understand anything and is unsure what is happening.

I disagree. 
Affected users will see this: 
![image](https://user-images.githubusercontent.com/67682506/104567958-b4c2c300-564f-11eb-9f44-58211f0f8a95.jpeg)

A click on "Mehr Erfahren" will bring the user to a FAQ entry which explains everything in detail. 

So or so this is o/t here so...

**Comment by ThisIsNotALoveSong** [comment]
@Ein-Tim:
yes this ist the message.
But when you wait for response for your corona-test and you are not sure wether this affects you or not.

**Comment by ndegendogo** [comment]
> first my doc, called me to tell me i am positive, then my healthdepartment called and finally after 4 hours the app went positive.

@dsarkar could you please ask the devs what is the current frequency of background task to poll for test results? 
I am aware that risk checking procedure is rate-limited to intervals > 4 hours from Apple side, and that a high frequency of BG task always eats a lot of battery.

**Comment by thomasaugsten** [comment]
The background task for test result fetching is scheduled for earliest time. At the moment our background task is executed every 2h. But this is influenced by the situation of the iPhone. With high usage, low battery or no internet the fetch is postponed. Test result fetching, key download and exposure check is executed in the same background task.

**Comment by ndegendogo** [comment]
Thanks @thomasaugsten.

As far as I understand, the key fetching is performed only while WLAN is availabe.
Does the same constraint apply also to fetching the test results?

**Comment by thomasaugsten** [comment]
Hourly key Download via wifi
Daily key download and test result fetching via mobile and wifi

**Comment by ndegendogo** [comment]
@thomasaugsten is it possible to "poll" manually more often when I am waiting for a test tesult? Even when I don't have WLAN at that time, only mobile data?
Because a delay of up to one day seems quite much in this situation (so it could be worth an enhancement request)

**Comment by thomasaugsten** [comment]
Open the app will refresh the test result and there is a refresh button in the test result pending screen

**Comment by Ein-Tim** [comment]
I suggest to close this (like #1703) since I think that with the FAQ articles in place and the today released version 1.12 everything should be clear. 
If there are any duplicates we can reopen this for long-term visibility.

**Comment by dsarkar** [comment]
@ouboub Do you want to close this issue as suggested by  @Ein-Tim? Thanks.

**Comment by ouboub** [comment]
done

**Comment by dsarkar** [comment]
@ouboub Thanks!

**Comment by dsarkar** [comment]
Related Internal Tracking ID: [EXPOSUREAPP-4906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4906)
