### ISSUE TITLE
Matched key count is > 0 but app still shows zero exposure

### ISSUE THREAD

**Issue by cricketsamya** [corona-warn-app/cwa-app-ios#1723]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue

## Your Question
Matched key count in the exposure setting is non zero but the app reports back no exposure. Is this correct behavior?

**Comment by heinezen** [comment]
Hey @cricketsamya ,

This is indeed correct behavior since CWA version 1.9 and the switch to Exposure Notification v2. On the OS level, Exposure Notification v2 logs every encounter, even if these have a very short duration and are far away. These encounters are very low risk, so the CWA does not consider them in the evaluation and filters them out. Encounters are considered if they pass a certain threshold for signal strength and duration.

You can find out more about this in our FAQ entry regarding risk assessment: https://www.coronawarn.app/en/faq/#risk_assessment

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by cricketsamya** [comment]
![image](https://user-images.githubusercontent.com/13750637/102718862-e368aa80-42ea-11eb-8a96-196156cba4fe.jpeg)

![image](https://user-images.githubusercontent.com/13750637/102718866-e6fc3180-42ea-11eb-8de2-3d70e972f79d.jpeg)

So pictures for reference!

**Comment by Ein-Tim** [comment]
Please see also #1703

**Comment by cricketsamya** [comment]
@Ein-Tim Now its more calculations! Checking it! Thanks!

**Comment by cricketsamya** [comment]
Thank you explanation guys!

**Comment by jucktnich** [comment]
Pls close
