### ISSUE TITLE
CWA or OS downloads too much batches and then confusion with matched keys

### ISSUE THREAD

**Issue by Platinum2018** [corona-warn-app/cwa-app-ios#1848]
## Technical details

- Device name: iPhone XS
- iOS Version: iOS 14.3
- App Version: 1.10.1 (0)

## Describe the bug

On January 23 my phone performed the exposure check on 01:16 am on it's own, while I was asleep.
It don't found matched keys, according to the os (Settings --> "Begenungsmitteilungen" --> "Begenungsüberprüfungen" --> "Date and Time" --> "Übereinstimmende Schlüssel: 0")
It downloaded 14 batches of datas. It seems like that it downloaded the batches for the last 14 days correctly.
Second check was performed at 06:17 am by myself, I opened the app. It also don't had matched keys, but it downloaded 19 batches, instead of 14. It looks like it downloaded the batches from the past 15-19 days also incorrectly.
Now it's becoming interesting. At 1:16 pm it performed the third check by it's own and displayed 1 matched key. Now it downloaded 26 batches instead of 14! 
At 5:15 pm the next auto check was performed and now it downloaded 30 batches! It also displays 1 matching key there.

----

So a short break for now. On which day it found the matched keys? I thought the app or iOS deletes every keys that are older than 14 days. It looks like it found a match with an key and batch from the past 15-30 days. To be clear, the past 15-19 days, as the one matching key pops up while it downloaded 19 batches. Interesting to know: When there is a matching key for example 17 days in the past, why I don't had matching keys since more than a month?! That doesn't make sense, does it?

----

Now, today (January 24), the next day. It performed the check again at 1:16 am on it's own and it downloaded 14 batches correctly. But to my surprise it still displayed one matching key. It checked 13 of 14 batches again, that it checked 24 hours before that check (and plus the new batch of the 24 january) and still found one matching key, but it doesn't found it 24 hours before on the first 14 batches. 
It also performed 3 more checks today (7:57 am, 1:16 am and 5:18 pm), found the matching key on all checks and also downloaded too much batches, with every check it downloaded more and more old batches, when I understand that right.

Maybe I only have an understanding problem here, or is it just an bug?
When was the encounter? Is the encounter just real or fake? How makes that all sense?
The CWA itself displays "Keine Risiko-Begegnungen". 

I also have an iPhone 8 with iOS 14.3 with me all the time and to my surprise, it doesn't found matching keys yesterday and today, but it also downloads too much batches after the first, normal check with 14 batches being downloaded.
Maybe it's because I have the iPhone 8 in my pocket and the XS more in the hand, while traveling with the train, bus, or walking through the city and the XS catched some bad signal, while the 8 can't get that through the pocket.

## Steps to reproduce the issue

 Exposure Notifications --> Exposure Checks --> Click on the first time on one day --> Look how many batches it downloaded and how many encounters you have
2. Later on the day when more checks are performed, check it again - it shows more that 14 batches that were downloaded now
-->

## Expected behaviour

I really don't know what's going on there

## Possible Fix

I don't know, how to fix that, but I think it just downloads too many old batches, that doesn't matter anymore (Bug in the app or maybe in iOS?). But when keys that are older than 14 days are being automatically deleted, why it seems to found matching keys in old batches - also why it doesn't found matching keys, while these old batches were in time (the last 2-3 weeks), but now? And why does it found the matching key on the new, first check today, while it just checked the same 13 batches (no key found yesterday), plus the batch from today?

## Additional context

Maybe I understand something wrong here and I would be happy when anyone could explain, what's going on. But a question from me remains: Once a batch for a day is downloaded, it can't be changed anymore, or can it? I mean, if it downloads the batch for today in the night, but the positive tested person submitted their positive result to other users on a time like 1 pm, it should show up as an encounter a day later for my understanding and can't be showed up on the same day, as their keys can't be included in the batch that was already downloaded for today.
Sorry for these long text, but I'm confused.
I really hope that this is not an duplicate topic, but I couldn't find anything similar to my issue. If it exist, please appologize and just close that!

I attached screenshots and the export of my exposure checks here. As it seems like github doesn't support .json files, I packed the export of the exposure checks to an zip archive and attached that here.

[ExposureChecks-2021-01-24.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5862939/ExposureChecks-2021-01-24.zip)

![image0](https://user-images.githubusercontent.com/26902365/105640317-b83f2100-5e7d-11eb-92cb-114184b142ef.png)
![image1](https://user-images.githubusercontent.com/26902365/105640318-b9704e00-5e7d-11eb-81e2-7455adb55bd7.png)
![image2](https://user-images.githubusercontent.com/26902365/105640320-ba08e480-5e7d-11eb-98a2-6c9c512dbc32.png)
![image3](https://user-images.githubusercontent.com/26902365/105640321-baa17b00-5e7d-11eb-8519-39f2da581e73.png)
![image4](https://user-images.githubusercontent.com/26902365/105640322-bb3a1180-5e7d-11eb-9b3e-99381c8e2367.png)
![image5](https://user-images.githubusercontent.com/26902365/105640324-bbd2a800-5e7d-11eb-9092-8f35c5265c8f.png)
![image6](https://user-images.githubusercontent.com/26902365/105640326-bc6b3e80-5e7d-11eb-8273-496e6b3e2aaf.png)
![image7](https://user-images.githubusercontent.com/26902365/105640327-bc6b3e80-5e7d-11eb-93b3-1639f18b77be.png)
![image8](https://user-images.githubusercontent.com/26902365/105640328-bd03d500-5e7d-11eb-8fa4-7837bd426b1d.png)
![image9](https://user-images.githubusercontent.com/26902365/105640329-bd9c6b80-5e7d-11eb-9311-8f9bbd188490.png)
![image13](https://user-images.githubusercontent.com/26902365/105640330-be350200-5e7d-11eb-99de-ed96c76e1804.png)
![image14](https://user-images.githubusercontent.com/26902365/105640331-becd9880-5e7d-11eb-9c72-4a77268861fd.png)
![image15](https://user-images.githubusercontent.com/26902365/105640332-becd9880-5e7d-11eb-834b-e284bb450082.png)
![image16](https://user-images.githubusercontent.com/26902365/105640333-bf662f00-5e7d-11eb-8540-e8d5a7c86abe.png)
![image17](https://user-images.githubusercontent.com/26902365/105640336-bffec580-5e7d-11eb-86ac-256a07aab592.png)
![image18](https://user-images.githubusercontent.com/26902365/105640337-bffec580-5e7d-11eb-9f5e-ab6b0fd82a40.png)
![image19](https://user-images.githubusercontent.com/26902365/105640339-c0975c00-5e7d-11eb-8560-fa692661778f.png)
![image20](https://user-images.githubusercontent.com/26902365/105640341-c12ff280-5e7d-11eb-8d5d-74a7f0c8a9be.png)

**Comment by Ein-Tim** [comment]
Hey @Platinum2018 👋

First of all, everything is working correct here! This is not a bug. 
I will explain everything in detail later, please give me some time.

Thanks

**Comment by Ein-Tim** [comment]
You have to know that since version 1.7, Corona-Warn-App downloads keys not only once a day, but every 4 hours (see [this](https://www.coronawarn.app/en/blog/2020-11-25-corona-warn-app-version-1-7/) blog post for more information).
So, there are no longer only the files of the last 14 days, but also files from every hour. This means that it is normal that the check does not only contain the files of the last 14 days, but also all hourly files from the hours that passed before the check.

I will give you an example with the data you provided.

The first check on your phone on 23.01.2021 happened at 01:16h. There 14 files, the files from the last 14 days were downloaded. 
Then, the next check happend at 06:17h (5 hours after the first check). So, this check, again, downloaded the files from the last 14 days **and** the 5 more hourly files which were already available at that time (for each hour since 01:16h one (1h, 2h, 3h, 4h, 5h)).
Now, at 13:16h the next check happened (7 hours after the second check) and downloaded the files from the last 14 days and all hourly files which were already published at that time (1h, 2h, 3h, 4h, 5h, 6h, 7h, 8h, 9h, 10h, 11h, 12h).
17:15h the next check. 14 files for the last 14 days and - correct 16 hourly files (1h-16h). 

In this check, one match was found - which should make sense now as you know that these are not any old files but rather very new one.

>Now, today (January 24), the next day. It performed the check again at 1:16 am on it's own and it downloaded 14 batches correctly. But to my surprise it still displayed one matching key. 

Correct, the hourly files all get summed up at the end of each day and are combined into one file which then gets distributed to all users the next day.

>When was the encounter? Is the encounter just real or fake? How makes that all sense?
The CWA itself displays "Keine Risiko-Begegnungen".

This is possible since version 1.9 of Corona-Warn-App, for more information see f.e. [this](https://github.com/corona-warn-app/cwa-documentation/issues/515) Issue. To give a quick answer: 
This encounter was recorded by the underlying framework, the ENF (Exposure Notification Framework) from Apple, but was below the threshold (even for Low-Risk encounters) so Corona-Warn-App filtered the encounter out.

>I also have an iPhone 8 with iOS 14.3 with me all the time and to my surprise, it doesn't found matching keys yesterday and today, but it also downloads too much batches after the first, normal check with 14 batches being downloaded.
Maybe it's because I have the iPhone 8 in my pocket and the XS more in the hand, while traveling with the train, bus, or walking through the city and the XS catched some bad signal, while the 8 can't get that through the pocket.

We had similar reports before - I think the answer to this is that the iPhone Xs has a better BLE signal reach and could so detect this very low risk encounter (probably the person was far away) and the iPhone 8 could not detect it with it's BLE signal reach.
Also, you have to know that your phone does not constantly searches for encounters - there are phases in which your phone only sends BLE beacons (which can be received by other phones) but in which it does not search for other BLE beacons. To learn more, please see: https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitations
So, another possible answer for this could be that somebody quickly walked only quickly briefly next to you (10s or so) and the iPhone Xs was searching for BLE beacons at that time, while the iPhone 8 wasn't.


>Once a batch for a day is downloaded, it can't be changed anymore, or can it?
Correct, old batches can't be changed anymore.


I hope I answerd your questions and helped you. If you don't have any more questions please close this Issue.
Thanks!

Stay safe and healthy!

**Comment by Platinum2018** [comment]
Thank you very much! I did not know, that there are new data's being published hourly. 
Now I understand it! Thanks and stay healthy too! 👍👋
