### ISSUE TITLE
[UI] Some icon sizes seem to be too large.

### ISSUE THREAD

**Issue by Bohne9** [corona-warn-app/cwa-app-ios#228]
The marked icons in the images seem to be too large in my opinion.

<img src="https://user-images.githubusercontent.com/24317813/83792946-183d4900-a69c-11ea-93e0-0ebac6f7003e.png" alt="drawing" width="200"/><img src="https://user-images.githubusercontent.com/24317813/83792951-196e7600-a69c-11ea-942e-425ae822bc69.png" alt="drawing" width="200"/><img src="https://user-images.githubusercontent.com/24317813/83792954-196e7600-a69c-11ea-9715-b6f998c23fa9.png" alt="drawing" width="200"/>

I changed some icons to either match the target size provided in Apples Human Interface Guidelines. In my opinion it looks better than right now what do you think about it?

<img src="https://user-images.githubusercontent.com/24317813/83792324-348cb600-a69b-11ea-867d-41d3be67d1fc.png" alt="drawing" width="200"/><img src="https://user-images.githubusercontent.com/24317813/83792333-36ef1000-a69b-11ea-8355-354dccb6dfb6.png" alt="drawing" width="200"/><img src="https://user-images.githubusercontent.com/24317813/83792337-38203d00-a69b-11ea-9e27-046161568bb6.png" alt="drawing" width="200"/>

**Comment by mariohamann** [comment]
Since older people - especially as a risk group - should also use the app without any problems, I think it's good to leave at least the buttons big enough.
Referring to the study [Target size study for one-handed thumb use on small touchscreen devices](http://dl.acm.org/citation.cfm?id=1152260) and [Designing For The Elderly: Ways Older People Use Digital Technology Differently](https://www.smashingmagazine.com/2015/02/designing-digital-technology-for-the-elderly/) a target size of at least 9.6mm should be kept.

**Comment by Bohne9** [comment]
Good point. 
But wouldn’t an approach where you have consistent icon/ button sizes which scale up as the user increases the size of the OS font be the “better” choice?

Especially since this would be an approach that is compatible with Apple’s accessibility features and provide users without any physical limitations a great user experience while maintaining accessibility for the ones who have physical limitations.
