### ISSUE TITLE
Unnecessary free space on top of "Transnational Exposure Logging" screen 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2414]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s / iPhone XR
- iOS version: 14.5 Public Beta 7
- App version: 1.15.2

## Describe the bug

There's an unnecessary free space above of the illustration in the "Transnational Exposure Logging" screen. This looks very strange in dark mode, because the dark color from the illustration isn't the same as the dark color of the background.

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on "Exposure Logging Active/Stopped" 
3. Click on "Transnational Exposure Logging"
4. See the free space above of the illustration

## Expected behaviour

No free space.

## Screenshots

<details>
<summary>Screenshots</summary>

iPhone 6s:

Light Mode:
<img src="https://user-images.githubusercontent.com/67682506/114279267-09e65900-9a34-11eb-83b7-1a3d68f9c5d9.PNG" width="300">

Dark Mode:
<img src="https://user-images.githubusercontent.com/67682506/114279268-110d6700-9a34-11eb-85b0-fb601d221718.PNG" width="300">

iPhone XR:

Light Mode:
<img src="https://user-images.githubusercontent.com/67682506/114279290-1e2a5600-9a34-11eb-91f7-e06a98a795e1.PNG" width="300">

Dark Mode:
<img src="https://user-images.githubusercontent.com/67682506/114279296-26829100-9a34-11eb-880d-933776bf1325.PNG" width="300">

</details>

---
Internal Tracking ID: [EXPOSUREAPP-6354](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6354)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, Internal Tracking ID: [EXPOSUREAPP-6354](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6354).

**Comment by ndegendogo** [comment]
The navigation item for this view controller is setup with a large title, although the title is empty. Hence the extra wide navigation bar.

*However, I have the suspicion that this was implemented intentional. We would get a transition from normal to Large titles, and this animation would look ugly in the current implementation, and was avoided. For this reason I guess this should be not fixed before #3372.*

**Comment by ndegendogo** [comment]
It is not an issue on iPhone 6 with iOS 12.5.3 (tested on true device).
It is an issue on iPhone SE with iOS 13+ (small screen, tested with simulator).

**Comment by ndegendogo** [comment]
PR #3442.

**Comment by Ein-Tim** [comment]
Thank you @ndegendogo!

**Comment by ndegendogo** [comment]
@dsarkar @heinezen could you please label this PR so that the devs are not too confused? 😅

Thanks

**Comment by Ein-Tim** [comment]
I can confirm that this has been fixed in version 2.10 (by @ndegendogo).

One small thing, in darkmode, there is still a visible (unnecessary) free space:

| How it is now | How it should be | 
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/134356778-c9707691-640c-40ac-8ef4-123566f908d4.png" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/134356799-59e330b2-c3c3-4b00-b04d-3a3903214983.png" width="300"> |

Maybe something for you @ndegendogo? But that's only a very minor thing.

**Comment by ndegendogo** [comment]
> One small thing, in darkmode, there is still a visible (unnecessary) free space:

@Ein-Tim only in dark mode, really? This seems strange ...

**Comment by jucktnich** [comment]
I **cannot** confirm a fix for iPhone SE 1

**Comment by ndegendogo** [comment]
> I cannot confirm a fix for iPhone SE 1

@jucktnich @Ein-Tim what do you propose then? Reopen this, or a new ticket?

**Comment by Ein-Tim** [comment]
@ndegendogo It's only visible in dark mode, sorry.

You can look into this, without an open issue. But as said, this is only a minor thing and isn't worth a new ticket (at the moment) IHMO.

**Comment by ndegendogo** [comment]
> One small thing, in darkmode, there is still a visible (unnecessary) free space:

@Ein-Tim I have just checked on the simulator. The **layout** in dark mode and in light mode match exactly (you can watch this if you toggle the appearance in the simulator menu).
Only in light mode, the color tone of the background of the artwork and of the table are the same (both RGB = 255/255/255), whereas in dark mode, the color tones are different (background of artwork RGB = 0/0/0, background of table RGB = 30/30/31).

At the moment I can only assume this is intentional. But this could be a question to the designers of the development team.

**Comment by ndegendogo** [comment]
@jucktnich may I ask for the iOS version of your SE 1? Is it a 12.5?

**Comment by ndegendogo** [comment]
@Ein-Tim actually, the runtime complains about a conflict in the layout.
So maybe this narrow dark-grey band between navigation bar and artwork is indeed an artefact of this layout conflict?

**Comment by Ein-Tim** [comment]
@ndegendogo 

Yeah, could be.
What would speak against to remove the narrow grey band over the illustration?

**Comment by jucktnich** [comment]
@ndegendogo I'm on iOS 15. But I don't think, that the space is bad for the UX, since it's not as big as it was.

**Comment by ndegendogo** [comment]
> What would speak against to remove the narrow grey band over the illustration?

You are right. It looks weird in dark mode.
And a PR would be the easiest way to get an opinion of the designers.

*So the next step would be to find out how to get rid of it - I'll try*

**Comment by ndegendogo** [comment]
> I'm on iOS 15

@jucktnich this is actually good news.
I don't yet if / how it is possible to test the cwa user interface with a 12.4 simulator, and Apple never released a simulator for 12.5.
So I'll ignore the iOS version (for the moment) and focus on trying to get a simulator with the screen size of SE 1 .... 🤪

**Comment by Ein-Tim** [comment]
@ndegendogo 

> So the next step would be to find out how to get rid of it - I'll try

Thank you! 👍

**Comment by ndegendogo** [comment]
The image of the European map is enclosed in a table cell. This cell has full screen width, but a [hard-coded height](https://github.com/corona-warn-app/cwa-app-ios/blob/7d1200b5e2518fa17ce437fe9d7eea71a813bb7f/src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewModel.swift#L28). The image is scaled **without distortion** to fit inside this cell. But the cell is a bit too high, so the background of the cell is visible.
Most of the images of cwa have a background color of RGB = 30/30/31 in dark mode, which blends perfectly with the table background. Only this image has a deep black background color of RGB = 0/0/0.

A solution would be to specify no explicit cell height, then the dark grey band disappears.

*(The alternate solution would be to give this cell a background color of RGB = 0/0/0 instead of RGB = 30/30/31, but I don't know how to configure that.)*

**Comment by Ein-Tim** [comment]
I am happy to confirm that this issue now has been finally fixed in version 2.12.

Here's a screenshot:

<img src="https://user-images.githubusercontent.com/67682506/137989573-8f11eb1a-dd96-4011-89f2-8fe76865e0d9.png" width="300">

Closing this issue as fixed in version 2.12.
