### ISSUE TITLE
Confusing message when deleting selfcreated QR Codes

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-app-ios#2588]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
When deleting selfcreated QR Codes within the app, the text assumes in my opinion that after deleting the QR Code it's invalid/disabled and not usable for other users with their devices anymore.

![QR_Code_Text](https://user-images.githubusercontent.com/82420268/116617030-b03fc300-a93d-11eb-9582-aed956627bd3.jpg)

## Suggested Enhancement
Redefine the confirmation text shown when deleting selfcreated QR Codes from the app. The text should inform that check in without scanning the QR Code is not possible anymore after deletion is complete.

## Expected Benefits
It's more clear what's happening when deleting selfcreated QR Codes from the list.

**Comment by Ein-Tim** [comment]
Hey @FlightMS 👋 

Thanks for contributing here! 

I'd suggest that we merge this with the wishlist item [Better warning when deleting an event registration QR code](https://github.com/corona-warn-app/cwa-wishlist/issues/482) https://github.com/corona-warn-app/cwa-wishlist/issues/482, which covers a quite similar thematic as this ticket here. 
Also, it suggests to clarify the warning, and this is also your suggestion.

If you don't think it should be merged this issue should be transferred to the wishlist repository, since it applies to iOS and Android.

Thanks and have a nice evening!

**Comment by FlightMS** [comment]
Hi @Ein-Tim,

unfortunately I haven't seen the other issue but that's already the issue I tried to explain in this issue. So of course please merge it to the other issue!

Since I don't know if the message is the same on devices with Android OS, I thought the best place for the issue was here..

Thank you for the information and have a nice evening too!

**Comment by Ein-Tim** [comment]
@FlightMS 

No Problem at all! As far as I know, the Error Message that's shown when deleting a QR-Code is the same on iOS and Android.

You as the author have the option to close this issue, you should see a button for this right next to the comment field (if you're using the GitHub website). It would be perfect if you could close this issue. 

Thank you!
