### ISSUE TITLE
UI: Overlapping text while creating Rapid Test Profile

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2699]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: iOS 14.5.1
- App version: 2.2.1

## Describe the bug

While creating the rapid test profile it is possible that the headline "Rapid Test Profile" overlaps with the information text below.

## Screenshot

<img src="https://user-images.githubusercontent.com/67682506/118323645-35f86c80-b501-11eb-91d8-ab929bfeec3c.PNG" width="300">

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on "Next Steps" inside of the "Register your Test" box
3. Click on "Create Rapid Test Profile"
4. Directly click into the field "Street and House Number"
5. See the overlapping test 

## Expected behaviour

The headline should disappear (get to the top) as when you scroll further down.

---
Internal Tracking ID: [EXPOSUREAPP-7295](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7295)

**Comment by jucktnich** [comment]
Not reproducible on iPhone SE 1 iOS 14.5.1 CWA 2.2.1

**Comment by Ein-Tim** [comment]
@jucktnich Quite sure this is device specific. 
I assume that this affects all iPhones which have the screen size of the iPhone 6.

**Comment by jucktnich** [comment]
Ok
Just wanted to be sure, it is not on small screen sizes.

**Comment by dsarkar** [comment]
Not reproducible on iPhone 6s iOS 14.4 CWA 2.2.1

**Comment by jucktnich** [comment]
On iPhone SE, the title is at the start in the header on iPhone 6 not, seems like this is the problem

**Comment by dsarkar** [comment]
font size?

**Comment by dsarkar** [comment]
@Ein-Tim  @jucktnich ok, happens with medium font size only, and only tapping in "Strasse"? @Ein-Tim Correct?

**Comment by jucktnich** [comment]
Btw Still not reproducible on iPhone SE 1

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7295](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7295)

**Comment by Ein-Tim** [comment]
@dsarkar 

>ok, happens with medium font size only, and only tapping in "Strasse"?

Yes, correct.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for confirming, that is also what I can reproduce. Internally reported that way. Enjoy weekend!

**Comment by ndegendogo** [comment]
I can reproduce this on the simulator on the current development branch (pre-release) as of today (06 Sept 2021, branch release/2.10.x, commit a43ff5a96f16ec695312ad050f8276bfc898874e) with the following sequence:

- precondition: no RAT profile available
- from Home tab, select test management
- scroll down and select 'create RAT profile'
- the form shows with normal title
- scroll down to reveal the large title
- select field "Strasse und Hausnummer"
- the keyboard appears and pushes the form up a bit so that the selected field is still visible
- but the large title remains and overlaps with the text.

cwa newest development / iOS 14.3 / iPhone SE

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-06 at 19 25 40](https://user-images.githubusercontent.com/6118267/132248915-00c64a8a-6620-4ebf-8d3b-265168e614a5.png)

**Comment by ndegendogo** [comment]
I volunteer 😎

**Comment by Ein-Tim** [comment]
Thanks @ndegendogo! 🚀

**Comment by ndegendogo** [comment]
In this scenario we see a similar effect, although weaker with a device with higher screen, like iPhone 8
(simulator / development branch as of today / iOS 14.3 / iPhone 8)

![Simulator Screen Shot - iPhone 8 - 2021-09-06 at 23 25 06](https://user-images.githubusercontent.com/6118267/132261356-131b52ef-743d-4e80-bbee-253c28e6d780.png)

**Comment by ndegendogo** [comment]
And it does not occur on iPhone 6 / iOS 12.5.3. In that configuration the modal views are presented with full screen height, whereas the newer iOS versions have a slightly reduced screen height, which results in a slightly different layout.

**Comment by ndegendogo** [comment]
The layout constraints in the animation when the keyboard appears (a) look differently than in a scrolling-up animation (b).
(a) the title remains in-place, and the form moves up towards the title, and even overlapping it.
(b) the form moves up together with the title, they keep constant distance.

**Comment by ndegendogo** [comment]
Same layout issue occurs with iOS 13.7. Tested on simulator with iPhone SE.

**Comment by dsarkar** [comment]
@ndegendogo Is the root cause of this issue here related to another issue you fix with https://github.com/corona-warn-app/cwa-app-ios/pull/3511?

**Comment by ndegendogo** [comment]
@dsarkar no, this is different *(and originally I had hoped the same...)* 😅

Actually, I think I have understood **roughly** what is going on. I am not sure that I already understand the root cause; and I have not yet found a working solution.

***So, maybe I share my insights so far.***

In the scenario, the following happens:
- user taps a field of the form
- keyboard starts to appear
- this triggers the form to scroll up, so that the field-to-be-entered is on the visible part of the screen and above the keyboard.
- the scrolling is animated, and the animation is synchronized with the keyboard.

All this is nicely implemented [here](https://github.com/corona-warn-app/cwa-app-ios/blob/0e84d49a7562bc58396face2fb84630056820930/src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift#L173)
But now the form moves up so far that the navigation bar is supposed to shrink. Only the navigation bar is not aware of this, and stays large.

And now I am guessing wildly: 🙃
- maybe the navigation bar misses a trigger to re-layout itself? 🤷
- maybe the layout constraints are setup wrong? 🤷
- maybe the wrong property is animated? 🤷

**Comment by dsarkar** [comment]
@ndegendogo OK, thanks for the insight! I will forward this to the internal ticket for the developers.

**Comment by ndegendogo** [comment]
This happens also on devices with small screen like SE first generation.
Click in the field for the surname.
See screenshot.

iPhone SE first generation (simulator) / iOS 15.0 (simulator) / cwa latest on branch release/2.15.x as of Nov 04

![Simulator Screen Shot - iPhone SE (1st generation) - 2021-11-05 at 17 36 33](https://user-images.githubusercontent.com/6118267/140546178-71cf1a2a-85db-49fe-87d7-3d191d1b1e14.png)

**Comment by dsarkar** [comment]
FYI PR: https://github.com/corona-warn-app/cwa-app-ios/pull/5014

**Comment by Ein-Tim** [comment]
I can confirm that this has been **fixed** with version 3.1, and I'm therefore closing this issue as completed.

**Comment by ndegendogo** [comment]
🎉
