### ISSUE TITLE
Wrong birthday is displayed after setting up an „Schnelltest Profil“

### ISSUE THREAD

**Issue by friedemannm** [corona-warn-app/cwa-app-ios#2760]
## Technical details

- Device name: iPhone 11
- iOS version: 14.4.2
- App version: 2.2.1

## Describe the bug

Birthday will be displayed wrong after setting up an "Schnelltest-Profil".

## Steps to reproduce the issue

- Create a "Schnelltest Profil"
- Set Birthday to 6.3.1989
- display the QR Code
- the birthday displayed in the info box under the QR code is wrong. It is 5.3.1989 instead of 6.3.1989

Im not sure if the data in the QR code is also wrong.

---
duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/2695
Internal Tracking ID: [EXPOSUREAPP-7263](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7263)

**Comment by Ein-Tim** [comment]
Hey @friedemannm 

Thank you for reporting this issue. We are aware of this bug and it is planned to be fixed in the next upcoming release, version 2.3. 

This was reported in #2695 before and is an error with the timezones. It only happens between 00:00h and 01:59h CEST.

The corresponding PR is: #2741.

I'd like to ask you to close your issue in favour of #2695, monitor this issue and follow up there if necessary.

Have a good night and stay safe & healthy!

**Comment by dsarkar** [comment]
@friedemannm Thanks for the report. As @Ein-Tim mentioned this will be fixed with release 2.3. In the meantime, create the profile at any other time, i.e. not between 0000-0200. Thanks, best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Fixed in 2.3

**Comment by dsarkar** [comment]
@friedemannm Thanks for reporting. Best, DS

---
Corona-Warn-App Open Source Team
