### ISSUE TITLE
I can get a negative test for the future at DM

### ISSUE THREAD

**Issue by krjw-eyev** [corona-warn-app/cwa-app-ios#2958]
## Describe the bug

If I register for 2 Tests, one the next day and one in 2 weeks time and I let DM scan the one in two weeks time. I can get a negative result for the second date.

Maybe this is DMs fault.

## Expected behaviour

DM should check for the date when scanning and your API should check the date of the test when registering.

## Steps to reproduce the issue

Register for 2 Tests, go to the first appointment, let them scan the QR-code of the second appointment.

**Comment by Ein-Tim** [comment]
Since this is a problem which also affects Android (I assume), I would like to ask whether this could be transferred (once again) to the documentation repository?
That would be nice, thank you!

**Comment by krjw-eyev** [comment]
Was that question directed at me? I don't know if Android is affected and I don't know how you process issues like these so you can do whatever you want with it :)

**Comment by Ein-Tim** [comment]
@krjw-eyev No this was not directed at you but rather at @heinezen or any other community manager here (: They can transfer this issue.

Have a nice evening.

**Comment by Ein-Tim** [comment]
@thomasaugsten Can this please be transferred out of the iOS repo? It is not iOS specific. 

BTW: It seems like DM does not offer corona rapid antigen tests anymore.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This issue is now obsolete and should probably be closed

> BTW: It seems like DM does not offer corona rapid antigen tests anymore.

That agrees with the dm website https://www.dm.de/services/services-im-markt/corona-schnelltest-zentren-613504

"dm-Corona-Schnelltestzentren
Liebe Kundinnen, liebe Kunden, wir bieten den Service unserer dm-Corona-Schnelltest-Zentren aktuell nicht mehr an. Vielen Dank für Ihr Verständnis. "

It means also that the blog post https://www.coronawarn.app/en/blog/2021-05-11-how-to-rapid-test-integration/ "Corona-Schnelltest per App: So funktioniert die Registrierung für dm, EcoCare und testbuchen.de/No-Q" is out of date.

**Comment by Ein-Tim** [comment]
@dsarkar See @MikeMcC399's comment above. Please close this issue.

**Comment by dsarkar** [comment]
Good morning @krjw-eyev, see the comments above, this issue is now obsolete. Thanks for reporting, please open a new issue if you want to report a bug, a suggestion, etc. Best wishes, DS

---
Corona-Warn-App Open Source Team
