### ISSUE TITLE
VC_NAME_MISMATCH error on importing second vaccination cert.

### ISSUE THREAD

**Issue by JKiBa** [corona-warn-app/cwa-app-ios#2975]
- Device name: Iphone 10 Pro
- iOS version: 14.6
- App version: 2.3.3

Hi, similar, but not Identical to #2969 I recieve an error on importing the second certificate into the app. In both orders it works to import one cert, but not the second.  Error VC_NAME_MISMATCH is raised. 

CovPass app accepts both certs simultaneously, there is no name mismatch visible on the EU vac cert printouts. 

Presumably there is a problem with Dr. Title which is stated before surname? Just a guess.

Thanks for investigating, JK

---
Internal Tracking ID: [EXPOSUREAPP-8069](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8069)

**Comment by dsarkar** [comment]
@JKiBa Thanks for reporting.

- The CovPass App can manage more than one certificate, for example of family members. If the name on both certificates is not exactly the same, it will still import the second certificate, but internally consider it as two different persons
- The CWA can manage only certificates of one person (this will change in a future release most probably). I.e., if the names are not exacly the same  (the difference might be even a white space), the CWA will not import the second certificate.

- In practice you don't need the first certificate. In the CWA you can delete the first one, and import the certificate of the second shot. After 14 days it will show full IMMUNITY in the app.

Hope that helps.

Best,
DS

---
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
Yes the Dr. in one of the certificates make it different but the 1/2 certificate is not important you need only the 2/2

**Comment by heinezen** [comment]
@JKiBa

Looks like the data for your first or second certificate might be entered differently by the issuer (e.g. your pharmacy). If you have received a printout of your certificates, you can quickly check if both certificates have matching data for:

* You surname and lastname
* Your data of birth

This data should also match with the data on your official passport oor Personalausweis because you need to show that during verification.

If you spot an error on the 1st certificate, you can delete it and just scan the 2nd certificate. This will be sufficient for CWA. If yoou spot an error in the 2nd certificate, you should get a re-issue of the certificate at your local pharmacy.

----
Corona-Warn-App Open Source Team

**Comment by MutzelMe** [comment]
I also got the VC_NAME_MISMATCH on my iPhone 7 today. On the 2nd paper certificate it looks like it accidently was set up with an additional space between my two forenames:
<forename1>SpaceSpace<forename2> so it does match the first certificate.

**Comment by Ein-Tim** [comment]
@MutzelMe 

As a workaround you can just import the certificate from the second shot, this is sufficient.

**Comment by MutzelMe** [comment]
Thanks @Ein-Tim, I did that and it looks good.

Since the double white space might be really hard to spot on the paper printout, this issue might also occur to other users without getting an idea what might be wrong.

Maybe its worth to think of replacing double/triple/quadruple :) white spaces with simple white space during the verification of the Firstname or Lastname.

As well as removing leading/trailing white spaces (maybe that's already implemented by CWA).

Thanks, for all your work. MM

**Comment by MarkusKuehbacher** [comment]
Same problem. The Dr. Title which is stated before my surname might be the problem.

**Comment by dsarkar** [comment]
@MarkusKuehbacher Thanks for reporting. As discussed above: Delete all certificates and just scan the second one. IMMUNTY should be displayed  after 14 days of second vaccination.


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Please close this issue @dsarkar.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. 

FAQ regarding this issue had been updated some time ago: https://www.coronawarn.app/de/faq/#vac_cert_mismatch
