### ISSUE TITLE
QR Code Vaccination Certificate cut off on smaller screens

### ISSUE THREAD

**Issue by bembeltogo** [corona-warn-app/cwa-app-ios#3184]
## Duplikate vermeiden
* [x] Diese Erweiterungsanfrage wurde noch nicht gestellt
* [x] Die Verbesserungsanfrage ist nur für iOS spezifisch, für allgemeine Probleme / Fragen, die für iOS und Android gelten, werfen Sie sie bitte in [CWA-Wishlist] auf (https://github.com/corona-warn-app/cwa-wishlist)
* [x] Wenn Sie eine neue Funktion vorschlagen, tun Sie dies bitte in [CWA-Wunschliste] (https://github.com/corona-warn-app/cwa-wishlist)

## Aktuelle Implementierung
Darstellung des Impfzertifikats in Version 2.5.1.  Der QR-Code ist bei 4,7" iPhones (iPhone 6/6s/7/8/SE2020) unten etwas abgeschnitten, daher kann er nicht sofort gescannt werden. Dies stört die Usability.

## Empfohlene Verbesserung
Platzieren des Button "Zertifikat hinzufügen" nicht über dem Zertifikat, sondern unter dem Zertifikat. Dadurch kann der QR-Code sofort verwendet werden.

## Erwartete Vorteile
Der QR Code kann ohne zu scrollen sofort gescannt werden.
![709E4D1E-0A87-4A79-9E44-805ED52FFDEC](https://user-images.githubusercontent.com/87539510/125980583-753ee977-b4bd-436b-a6e0-aebdab96b4b3.jpeg)

----
Internal Tracking-ID: [EXPOSUREAPP-8479](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8479)

**Comment by Ein-Tim** [comment]
**Translation:** 

## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Vaccination certificate display in version 2.5.1. The QR code is a bit cut off at the bottom on 4.7" iPhones (iPhone 6/6s/7/8/SE2020)so it cannot be scanned immediately. This disturbs the usability.

## Suggested Enhancement
Place the "Add Certificate" button below the certificate instead of above it. This allows the QR code to be used immediately.

## Expected Benefits
The QR code can be scanned immediately without scrolling.
*Picture see above*


---

Adding here, also the iPhone SE 1. Gen is affected by this, but since I don't own one, I can't check whether placing the button on the bottom would improve the situation there.

**Comment by jquade** [comment]
This issue also exists on iPhone 12 mini with non-default text size setting. The certificate QR code is partly obscured by the toolbar at the bottom of the screen.

**Comment by Ein-Tim** [comment]
This issue persists in version 2.20, where the button was removed and replaced with text.

**Comment by dsarkar** [comment]
@bembeltogo @Ein-Tim Thanks for reporting, however, for the moment it was decided that design won't be changed. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> I think this currently works as designed right?

> yes, as the button on top is consistent throughout the app. In case the user has scrolled once and doesn't close the app, they will also stay in that position with the full qr-code visible whenever coming back.
As the universal scanner is in place now, we could also think about removing it all together. We refrained from it for now to not disrupt users who got to know the pattern as is. Of course this would need to be done than for all other cases like Check-ins and so on as well and would need to be communicated accordingly, so I think it's out of scope for this bug.
