### ISSUE TITLE
[Statistic Cards] 7 Day average calculation of warnings seems to be wrong

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#3359]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.7.1
- App version: 2.6.3

## Describe the bug

When I use the numbers of warnings shared by the CWA, sum up the last 7 and divide them by 7, my calculated average is 533. 

![image](https://user-images.githubusercontent.com/873028/129441376-0c1e9286-0a68-4e33-8591-11bdadd7533d.jpeg)

The CWA however claims it is 462. This doesn't seem right. 

![image](https://user-images.githubusercontent.com/873028/129441407-f2a691b8-12a2-4d9e-8434-e60a4b79c35c.jpeg)

Unsure how the average is calculated, but it is different from my calculations based on the same numbers. 

## Steps to reproduce the issue

1. Collect numbers for a week
2. Calculate average
3. Compare

**Comment by Jo-Achim** [comment]
If the numbers in the "Positive" column are correct, then your average result of 533 is likely to be wrong.

Which formula and which numbers were used for the calculation?

Because the 7-day average value from the "Positive" column starting with 699 (Yesterday (13.08.)) + 526 + 590 + 631 + 334 + 129 + 324 (07.08.)) = 3233 / 7 = 469 (rounded). 

Or am I wrong?

**Comment by jwildeboer** [comment]
Correct. My formula is wrong. It somehow switched from using 7 to 8 days. Will close.
