### ISSUE TITLE
Validity check only works one time

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#3414]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.7.1
- App version: 2.8.0(4)

## Describe the bug

When you check validity of certificate for entry, rules are checked and everything is good. 

BUT when you check again for another country, check always fails.

You have to restart the Corona Warn App to get a succesful check. 

## Steps to reproduce the issue

1. open Certificate
2. check validity for, say, Austria. 
3. check succesful
4. check again for another country, say Belgium
5. check fails
6. restart app
7. check works for denmark but all subsequent checks fail again

![image](https://user-images.githubusercontent.com/873028/130765688-539d17a1-ca81-4ecf-9b40-2f788a357cfa.jpeg)

**Comment by Ein-Tim** [comment]
@jwildeboer 

Are you aware that Denmark did not provide any rules? 

<img src="https://user-images.githubusercontent.com/67682506/130764010-e49219e4-b9be-4d7b-9623-87040df1b17f.jpeg" width="300">

**Comment by jwildeboer** [comment]
I tested it with Austria, Netherlands, Denmark, Belgium. ![image](https://user-images.githubusercontent.com/873028/130764654-f69ee4ca-9153-4f96-bffb-b841a999893d.jpeg)

![image](https://user-images.githubusercontent.com/873028/130764712-9275f9bf-e31f-4f13-a2f1-4012aa3725a2.jpeg)

Do they all lack rules?

**Comment by Ein-Tim** [comment]
All of them but the Netherlands lack rules.
Sure about the Netherlands? Please try again.

**Comment by Ein-Tim** [comment]
Which type of certificate do you use? Vaccination, Test or Recovery?

**Comment by jwildeboer** [comment]
Hm. Why did it work before the update? I tested this extensively while hunting down the "Netherlands fail with a Schema v1.0 certificate"

Or asked the otherxway round - of what use is a validity check when there are no rules? Shouldn't those countries be excluded from selection?

**Comment by Ein-Tim** [comment]
@jwildeboer 

Before version 2.8 countries with no rules were just shown as "Valid" (similar to what CovPass does in the current version). 
After community feedback (https://github.com/corona-warn-app/cwa-documentation/issues/678) it was decided to change the behavior so that countries with no rules no longer just show as "Valid" but show the "Certificate Cannot Be Validated" status.

> Or asked the otherxway round - of what use is a validity check when there are no rules? Shouldn't those countries be excluded from selection?

I suggest to open a new issue reg. this in the wishlist repository.

**Comment by thomasaugsten** [comment]
Before it was the same only the icon was green and the header text was different. The detail text was the same.
This not so easy because a country can have no rules for the specific date or for the specific certification type. 
It will also raise the questions why is the country not in the list is traveling not allowed for this country or my certificate not accepted in this country.

**Comment by jwildeboer** [comment]
I will create a new issue as I now understand better what's going on.
