### ISSUE TITLE
Enable Developers to disable Certificate Pinning

### ISSUE THREAD

**Issue by ChristianKienle** [corona-warn-app/cwa-app-ios#358]
#301 will enable certificate pinning on all environments. We should find a way to still be able to disable pinning for development purposes since it make debugging the HTTP layer terribly inconvenient.

At the same time we have to keep security considerations in mind. There should not be any hidden setting or runtime capabilities to disable pinning. We should maybe consider having a separate target for developers. This way pinning becomes disabled/enabled at compile time rather than runtime.

**Comment by haxxbard** [comment]
My personal wish would be to never allow this at runtime and would propose a second build process, building the development version which contains special functions (e.g. to disable certificate pinning) instead of using only one app which contains "special functions". It should be also technically impossible to release the development app to endusers.

**Comment by sebastianpicklum** [comment]
We could exclude certificate pinning for debugging builds. 

Or disable it using another scheme. I think excluding Certificate Pinning for builds using the ENACommunity scheme would make sense and would not require adding another scheme.

I don't think there is a way to get any development build to endusers. The App needs to be distributed through the App Store or Test Flight which in both cases will trigger a review at Apple. The entitlement to use the exposure notification app is also locked to SAP, so that no other developer could even build a working app that uses the Exposure Notification API (the community build just mocks the API to enable other developers). 
Using fastlane should even make sure that no development build gets submitted to the App Store by accident.
