### ISSUE TITLE
Simulator: Choosing "fake" HC1/HC2 leads to invalid signature error

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3631]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Pro Simulator
- iOS version: 15.0
- App version: Simulator on branch `release/2.12.x`

## Describe the bug

Selecting the universal QR code scanner on a simulator and then selecting either "HC1" oder "HC2" in the pop-up "Select a QRCode you want to fake" leads to an invalid signature error. 

## Steps to reproduce the issue

1. Open the Corona-Warn-App on your Simulator branched from `release/2.12.x`
2. Click on the tab in the middle (the QR code icon)
3. Select either "HC1" or "HC2" from the pop up
4. See the invalid signature error.

## Expected behaviour

It should be possible to import certificates without a valid signature to a Simulator.

## Possible Fix

Disable signature check for Simulators, maybe via the "Override App Features" option in the Developer Menu?

## Additional information

This can be tracked in an internal ticket with #3632.

----
Internal Tracking-ID: [EXPOSUREAPP-9765](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9765)

**Comment by ndegendogo** [comment]
@Ein-Tim Actually, the "fake" certificates indeed have an invalid signature. So the behaviour to reject them is correct (we want to be able to debug even the cryptographic operations like signature verification on the simulator).

If I understand your wish correctly, you want a variant where the signature verification of these fake certificates is "mocked" so that they are accepted and can be stored, and that you can use them to test the behaviour of the app with certificates present.

Please try ["Whiskey's debugging trick"](https://github.com/corona-warn-app/cwa-app-ios/issues/3804#issuecomment-963289065) if it fulfils your wish.

Note: meanwhile the fake certificates are outdated. So you can scan and store them, but still they are shown as invalid.

**Comment by Ein-Tim** [comment]
I meanwhile consider this as intentional. Thus closing this issue.

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-app-ios/pull/4730
