### ISSUE TITLE
Received red warning for day I spent at home

### ISSUE THREAD

**Issue by BerGer23** [corona-warn-app/cwa-app-ios#3900]
Hi,

I received a curious red warning for a single encounter that happened on 23.11.
To the best of my recollection (verified by memory + checking bank account and credit card) I literally spent the whole day indoors.
The only person I encountered is the one living with me, they did not report a positive test.
It is an apartment in the inner city, on ground level. 
We share walls with two neighbours. The street next to the apartment is frequently used.

The documentation in https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md says:
`Under perfect circumstances, i.e. without any obstacle in the signal pathway (see also section "Consequences and Constraints"), each dB value is associated with a particular distance. All encounters for a diagnosis key that lasted less than 10 minutes in total (regardless of how close the smartphones came during that time) or during which the smartphones were more than 8 meters (>73 dB attenuation) apart on average (regardless of how long the encounter lasted) are discarded as negligible risk.`

I interpret this as only encounters lasting >10m with signal strength >73dB are able to trigger a red warning.
Sounds to me like people standing by the window or neighbours behind the walls cannot cause this - but no idea what the alternative would be.
The rotating keys are generated by the phones, right - but it must be super unlikely two of those collide (in a fixed timeframe even)?
I'm stumped - any insight & ideas what could have caused this?

I am using the iOS version, hence opened this here - feel free to move it to another project.

**Comment by Ein-Tim** [comment]
Good Morning @BerGer23!

Please note that the document you quoted is heavily out of date: https://github.com/corona-warn-app/cwa-documentation/issues/453

In general, these issues are very hard to investigate, as because of the high level of privacy and anonymity, the app does not provide any details about the encounter to the user. The only thing we could do here is the same as you: Guess.

I'd guess that an infected person visited one of your neighbors or was waiting for something in front of your house. 

I also had two high risk encounters on a phone which never left my flat, in the end, it was clear that they were because the visitors of neighbors which live on the other side of the street were tested positive.
