### ISSUE TITLE
RAT profile: Text moves

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4415]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.4.1
- App version: 2.20.3

## Describe the bug

The text
"Bitte zeigen Sie diesen QR-Code an der Teststelle vor, um Ihre persönlichen Daten schnell erfassen zu lassen. Bitte halten Sie zusätzlich Ihren Personalausweis bereit." moves:

https://user-images.githubusercontent.com/67682506/161422866-ad744735-b178-4564-8dcb-7c913ee170a8.MOV

## Steps to reproduce the issue

1. Click on the "Manage Your Tests" box
2. Click on "Rapid Test Profile"
3. Create a profile and/or do as I did in the video

## Expected behaviour

Text should not move.

---
Internal Tracking ID: [EXPOSUREAPP-12584](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12584)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12584](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12584)

Does this issue occur for you regardless of where you have scrolled on the page? For example, this was not reproducable for us until we scrolled down so that only the upper edge of the QR code was visible. (iPhone 11 Pro Max, iOS 15.4)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh Confirm, this does only happen when the upper corners of the QR code are not visible anymore.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4582

**Comment by Ein-Tim** [comment]
This issue has been fixed in version 2.23.1. 

Closing as fixed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting and confirming the fix. Forwarded to internal ticket.
