### ISSUE TITLE
Fehler 13 - problem persists after 24 hrs

### ISSUE THREAD

**Issue by Anonymous170722** [corona-warn-app/cwa-app-ios#4676]
My Corona App hasn’t refreshed since a week now, showing the error code „Fehler 13“. 
Please check. 

![9A866240-216A-43BA-B680-65859E0EAA3B](https://user-images.githubusercontent.com/109452515/179386113-c9cdba8c-6d6b-4239-9a24-851c8a416509.png)

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Anonymous170722** [comment]
IOS 15.5
iPhone XR
Corona Warnapp Version: 2.24.1

**Comment by Anonymous170722** [comment]
![Uploading A29AF1EE-E461-48B8-B3E8-3604E420C7C9.png…]()

**Comment by Ein-Tim** [comment]
Hey @Anonymous170722

Please, could you enable error logging like this:


1. In der CWA auf dem Reiter "Status" ganz nach unten scrollen
2. Auf "App-Informationen" scrollen
3. Auf "Fehlerberichte"
4. Auf "Starten" tippen
5. Einmal _machen_, dass der Fehler auftaucht
6. Schritte 1-3 wiederholen
7. Auf "Fehlerbericht senden" tippen
8. Auf "Einverstanden und senden" tippen
9. Nach unten scrollen
10. Auf "ID-Historie" tippen
11. Die jeweilige ID hier in den GitHub Issue stellen
 
---

After you did this, please perform the following steps to fix the problem:

1. iOS-Einstellungen öffnen
2. Bis zu "Begegnungsmitteilungen" scrollen & "Begegnungsmitteilungen" antippen
3. Auf "Corona-Warn-App" ("Aktive Region") tippen
4. Auf "Corona-Warn-App" tippen
5. Runterscrollen
6. "Begegnungsinformationen teilen" deaktivieren
7. Etwas mehr als 24 Stunden warten
8. Schritte 1-5 wiederholen
9. "Begegnungsinformationen teilen" aktivieren
10. Oben auf den blauen Text "Als aktive Region festlegen" tippen
11. CWA öffnen und prüfen ob alles wieder funktioniert

**Comment by Anonymous170722** [comment]
![3B47CFAC-130B-4799-A7BE-F5B1FD37D846](https://user-images.githubusercontent.com/109452515/179396209-f2dcae45-bba7-4dd3-aa63-71255c43cd71.png)

**Comment by thomasaugsten** [comment]
We need an error report over 24h. Please post the new id in 24h again

**Comment by Anonymous170722** [comment]
![Uploading 84A4FFBA-6F96-45D9-94B5-EC8C6A039E34.png…]()

**Comment by Anonymous170722** [comment]
Ok, I will send a new report tomorrow. Thank you

**Comment by dsarkar** [comment]
@Anonymous170722 Thanks for reporting. please see 

https://github.com/corona-warn-app/cwa-app-ios/issues/4676#issuecomment-1186497163
> We need an error report over 24h. Please post the new id in 24h again


Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Anonymous170722** [comment]
Still not working.

**Comment by thomasaugsten** [comment]
It looks like a network issue
Cann you access on your phone this urls:

https://verification.coronawarn.app/version/v1
Whitelabel Error Page
https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/EUR/date
List of dates

**Comment by thomasaugsten** [comment]
Identical to:
https://github.com/corona-warn-app/cwa-app-ios/issues/4462

**Comment by Anonymous170722** [comment]
![0FD0691A-2908-4F77-8659-C5DA86FC678E](https://user-images.githubusercontent.com/109452515/179575949-b628fcfb-3bdd-4ced-9838-709eab30140a.png)
![284D6385-E5A1-475D-BC5A-715B7994E33A](https://user-images.githubusercontent.com/109452515/179575953-35a6faf6-4f8e-41a4-a911-b15016e63508.png)

No, I am sorry, I cannot open these.

**Comment by mlenkeit** [comment]
After evaluating the error logs that we got, it seems as if the analysis from https://github.com/corona-warn-app/cwa-app-ios/issues/4462#issuecomment-1122082267 wasn't quite accurate.

The error message `Unsupported protobuf type: 4` also pops up here, but the `4` doesn't seem to refer to the Protocol Buffer data type `sint32`, but to a [lower-level type](https://github.com/rettichschnidi/ExposureNotification/blob/2dc4eb3d183142112bd60b7dea44f28becce4baf/File%20Signature%20Validation/ENProtobufUtils.m#L27) that when encountered [throws the error message](https://github.com/rettichschnidi/ExposureNotification/blob/2dc4eb3d183142112bd60b7dea44f28becce4baf/File%20Signature%20Validation/ENProtobufUtils.m#L208) in ENF.

We still don't fully understand why this error happens in ENF.

Our assumption is that for some reason, ENF fails to parse the key file, perhaps because the file got corrupted on the device or it fails to correctly load the file into memory. A corrupted key file on CDN seems to be unlikely, because a lot more devices would be affected then.

Our proposal to address this is to clear the cached key files when the error happens such that they are downloaded again next time. This would technically be similar to an in-app reset (with regards to what happens to the key packages then), which usually seems to solve the problem.

**Comment by Ein-Tim** [comment]
@mlenkeit Thanks for sharing your findings! Is there already a plan for with which version this fix will be shipped.

**Comment by Ein-Tim** [comment]
@Anonymous170722 

Hey, could you please update to version 2.25 and check if this update fixed the issue?

**Comment by Anonymous170722** [comment]
Hi Tim,

Thank you, my App is working again and checking for potential Covid encounters. 

Thanks for helping me!

Von meinem iPhone gesendet

**Comment by larswmh** [comment]
Thanks to all participants.

As this was solved in version 2.25, I'm now closing this issue as completed.
