### ISSUE TITLE
Validity of Certificate test should always have the current date and time pre-filled

### ISSUE THREAD

**Issue by skra72** [corona-warn-app/cwa-app-ios#4825]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Currently when opening the 'Validity of Certificate' screen the values under 'Check for' are pre-filled with the data the last time such a test was done. Actually this means that most of the time the pre-filled date is in the past.

## Suggested Enhancement
Instead of suggesting a check date in the past the app should always pre-filled the Date and Time selector with the current date. 

## Expected Benefits
Does it make sense to check the validity for some time in the past? So one benefit would be to avoid errors when a certificate is validated, especially as the app gives some strange error about missing rule sets when a past date is used.

And user could more quickly validate their current vaccination status.

---
Internal Tracking ID: [EXPOSUREAPP-14095](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14095)

**Comment by Ein-Tim** [comment]
Thanks for reporting this issue!

This was fixed before (version 2.23) but it seems like the change was reverted later.

Here's the issue I opened back when the feature was implemented: https://github.com/corona-warn-app/cwa-app-ios/issues/3839

**Comment by Ein-Tim** [comment]
@dsarkar 

While the picker was changed so that the user can't select dates in the past, the "default" date isn't now but rather the last time the feature was used. Thus a check against a date in the past is still possible.

Here are two screenshots where you can see this problem.

<img src="https://user-images.githubusercontent.com/67682506/194807230-08458aa0-3797-402f-9207-10b68b579034.png" width="300">

<img src="https://user-images.githubusercontent.com/67682506/194807273-091d9216-c7a3-4c54-996d-e5036c81b8d1.png" width="300">

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks, got it!

**Comment by dsarkar** [comment]
@skra72 Thanks for reporting, we will create an internal ticket.

**Comment by 30mar** [comment]
will set to obsolete as the effect is only until  31.4.2023
