### ISSUE TITLE
Link to the bluetooth settings instead of the app settings

### ISSUE THREAD

**Issue by felixbohnacker** [corona-warn-app/cwa-app-ios#626]
## Current Implementation
Currently, the link to open the device settings that is shown if you have Bluetooth disabled links to the settings for the Corona-Warn-App.

## Suggested Enhancement
Clicking on "Geräte-Einstellungen öffnen" should directly open the Bluetooth settings. Other apps (example: Nikon SnapBridge which I use to connect to my camera via Bluetooth) are capable of this.

## Expected Benefits
You don't have to navigate to the Bluetooth settings any longer in order to enable Bluetooth.

**Comment by steins-code** [comment]
The Bluetooth settings cannot be directly opened from iOS 10 upwards as its private API. Would be rejected by Apple during review.

**Comment by felixbohnacker** [comment]
@steins-code I wasn't aware of that, thank you for the information. Too bad 😕

**Comment by MauriceArikoglu** [comment]
@steins-code @felixbohnacker 
Actually that's not true. There is a legal workaround to open the Bluetooth settings directly.
Refer to: https://developer.apple.com/documentation/corebluetooth/cbcentralmanageroptionshowpoweralertkey

Before using bluetooth you would instantiate a `CBCentralManager` with the `CBCentralManagerOptionShowPowerAlertKey` with value `true` in an options dictionary passed on 
```
init(delegate: CBCentralManagerDelegate?, 
queue: DispatchQueue?, 
options: [String : Any]? = nil)
```
If bluetooth is enabled the delegate will be called, otherwise the user is prompted to open the Settings to enable Bluetooth.
CBCentralManager also has various properties informing about its state checkable from the delegate callback.

So this is possible. Question is whether it's actually worth the effort of implementing.
