### ISSUE TITLE
Minimum iOS Version is unacceptable

### ISSUE THREAD

**Issue by alinach120602** [corona-warn-app/cwa-app-ios#640]
Having the iOS App require Version 13.5 of iOS is unacceptable People still have old phones.
The Corona Virus is a Global Pandemic and not everyone has an iPhone 6s or later some people are still running on iPhone 5. I'm using an iPhone 6 which can't update past iOS 12. And it can't be that people without the latest iPhone aren't allowed to be healthy.
As a developer myself I know that downgrading the iOS SDK isn't as easy as 1-2-3 but please, do it for the people in need. Having such high System Requirements only leads to bad / hacky forks and old code bases.
And more people getting sick than needed.

Regards,
Alina / Veemyu

**Comment by benekuehn** [comment]
Hi Alina.
As this project uses the exposure notification API by Apple, there is no way from a developer standpoint to influence the minimum requirements. The Exposure notification framework is only part of iOS versions 13.5 and newer. As long as this project sticks to using the API which I highly recommended, Apple has to make it available for older versions. 
But iOS 13.5 is available for devices back to the iPhone 6 (launched in 2014) and iPhone SE.

**Comment by nathanlesage** [comment]
> As a developer myself I know that downgrading the iOS SDK isn't as easy as 1-2-3

The main problem is not necessarily the framework; but rather that the application relies upon the notification framework provided for by Apple which the company decided to only make available in iOS 13.5. This is necessary because some form of central exchange for the random UUIDs (what's called "random ID" are UUIDs, am I right?) is necessary, and this has been implemented by Apple (and Google), but the official app is unable to influence this. But you are indeed right, and backports should be made available. But therefore we'd need public pressure on both Apple and Google to backport that feature to older versions of their operating systems.

More info here: https://developer.apple.com/documentation/exposurenotification

**Comment by SebastianWolf-SAP** [comment]
The correct answer was already given by @nathanlesage. Thanks for that. We are closing this issue...

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by Iranite** [comment]
How Do we put pressure on Apple and Google then? Isn't this "feature" going to put people who can't afford new phones in an even further disadvantage, than they already are?

**Comment by alinach120602** [comment]
Exactly what I was thinking. Maybe change.org can help
