### ISSUE TITLE
Method of verifying that the App Store build is using the open-source code

### ISSUE THREAD

**Issue by LeSchlongLong** [corona-warn-app/cwa-app-ios#649]
## Current Implementation

You guys did a pretty good job regarding security. But a guarantee that you are using this code would be great. I would like a way to verify the integrity and authenticity of the cwa-app on iOS and Android. By that I mean a way to check that the code you guys compiled and published on the app/play store wasn't injected with additional code and is the same as the open source code published here on Github. While in theory you could just get the .ipa file and decompile it, in reality you need to get past apple's proprietary DRM-protection encryption, which is not that easy.
## Suggested Enhancement

On desktop applications you can usually verify a file's integrity by using SHA256 or SHA checksums, provided that the entity which compiled the application gives you these sums. I do not know whether this can be done to verify mobile apps, but giving users the possibility to check the authenticity of the compiled version would be great.
## Expected Benefits

I have noticed a lot of people asking this question:"How can I be sure that the open source code is actually being used?" Since there is and has always been a lot of skepticism about tech like this in Germany, I would expect a bigger acceptance of the app, when implementing such verifying methods.

**Comment by BjoernPetersen** [comment]
This also been discussed in the documentation repo: https://github.com/corona-warn-app/cwa-documentation/issues/14

**Comment by thomasaugsten** [comment]
Do you need additional information about the build to do a reproducible build with this manual?
https://core.telegram.org/reproducible-builds

**Comment by Giszmo** [comment]
I'm working on monitoring wallet apps for Android in an automated fashion and would like to extend it to corona apps as there appears to be more demand than for Bitcoin wallets for reasons I don't fully understand.

Anyway, what I have so far:

* An [Android app](https://gitlab.com/walletscrutiny/walletscrutinyandroid) that monitors updates and gets triggered by reproducible apps (hand selected 6 Bitcoin wallets out of 155 analyzed apps which almost all were not open source or reproducible).
* App update gets hashed.
* Hash gets sent to the server.
* If server doesn't know that hash, app update gets sent to server.

I have to manually run [this test script](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/blob/master/test.sh) on the files and as no app provider committed to not break my scripts so far, it often requires changes in the test script to get to a result like:

```
Results for 
appId:          de.schildbach.wallet
apkVersionName: 8.02
apkVersionCode: 802
apkHash:        f01e4028778bc2036902af2253522b7de0eb40ca3bff50f51a8c0918737fd6b4

Diff:
Files /tmp/fromPlay_de.schildbach.wallet_802/apktool.yml and /tmp/fromBuild_de.schildbach.wallet_802/apktool.yml differ
Only in /tmp/fromPlay_de.schildbach.wallet_802/original/META-INF: BITCOIN-.RSA
Only in /tmp/fromPlay_de.schildbach.wallet_802/original/META-INF: BITCOIN-.SF
Files /tmp/fromPlay_de.schildbach.wallet_802/original/META-INF/MANIFEST.MF and /tmp/fromBuild_de.schildbach.wallet_802/original/META-INF/MANIFEST.MF differ
```

which I then publish on [this website](https://walletscrutiny.com/).

Now my focus are Bitcoin Wallets but I released almost all as open source, so if the findings are interesting but somebody else wants to step up and run a coronascrutiny service, that would also be an option. I just hope there are synergies. I would also be very interested in adding it to the same site.

Currently the biggest hurdle is probably to get the binary updates for iPhone in a comparable way as I hope to soon collect the Android updates: On user devices as they happen. The problem is that those marketplaces can release different apps to people depending on device, language, country, ... and basically could even release a modified version to named individuals (not that Google would need a Corona app to spy on you).

**Comment by mynchau** [comment]
As BjörnPetersen has already mentioned it earlier, I'm closing this issue as this one is already open: corona-warn-app/cwa-documentation#14 Thanks for your contribution. We will follow up on this issue. 
Best regards
MC 
Your Corona Warn-App Open Source Team
