### ISSUE TITLE
Privacy protection window never shown

### ISSUE THREAD

**Issue by theboywholived8500** [corona-warn-app/cwa-app-ios#666]
## Describe the bug

Since the app shows very private and sensitive data there needs to be some kind of shield when entering the App Switcher so these informations can not be accidentally seen by other people. Though this kind of protection is already implemented it never really gets called. 
## Expected behaviour

When entering the background the Privacy protection window should appear 
## Steps to reproduce the issue

1. Swipe the app up and release the bar --> App Switcher mode
2. Data is still visible 

## Technical details

Device: iPhone X
Version: iOS 13.5.1

**Comment by lennartschoch** [comment]
Pretty sure this is more of an enhancement than a bug^^

**Comment by theboywholived8500** [comment]
I mean its not a critical bug ^^... but it is still something which doesn't work.

**Comment by tens0rfl0w** [comment]
This got changed one week ago. Before that change the Privacy Protection Screen was shown immediately after the app was backgrounded. Now the privacy protection screen gets activated after the app loses focus. To trigger that screen now do the following: Open the App, go to the home screen and then open the App Switcher. If you open the app switcher from the app directly it does not get triggered due to focus.

I wouldn't describe this as a bug, it is more a design question.

**Comment by theboywholived8500** [comment]
Ok now it makes sense. I just implemented this and called the protection in `sceneWillResignActive ` instead of `sceneDidEnterBackground`. Which works also when entering the switcher from the app directly. But yeah you are right... just wondered because I saw many app doing this.
