### ISSUE TITLE
Provide statistical information on overall exposure (per period)

### ISSUE THREAD

**Issue by hblaschka** [corona-warn-app/cwa-app-ios#678]
## Problem and motivation
In order to keep people motivated to use the app it would probably be helpful to provide some statistical information on the start page, to make it more dynamic and show some dynamic numbers (if possible at all due to API restrictions).

I am thinking about locally available statistical information like the number of individual overall exposures in specific periods (e.g. day, current week, last week, current month, last month, overall).

On top of that the overall number of installations (as already suggested elsewhere) would also be helpful if possible without breaking the anonymity of users.

**Comment by jlnprssnr** [comment]
The respective Android issue that was closed: https://github.com/corona-warn-app/cwa-app-android/issues/492

**Comment by bufemc** [comment]
Hint: there is also a nice list of ideas in the Android section, but it's in German:
https://github.com/corona-warn-app/cwa-app-android/issues/615

Of course depends what the Exposure APIs on both OS can deliver..

**Comment by corneliusroemer** [comment]
Something may be possible, one has to look into what exactly the Exposure API provides. I don't think that "nothing" is the answer.

**Comment by inf2381** [comment]
https://github.com/corona-warn-app/cwa-app-ios/issues/723#issue-641900301 
> It would be highly interesting to have a dashboard with statistics included!
> 
> How many contacts you had during a day:
> Total / per Hour
> Number of Cell Phones with Bluetooth
> Number of Cell Phones with Corona-Warn-App
> 
> And also a view that shows how many contacts you had within a special duration (histogram):
> <1m
> <5m
> <10m
> <15m
> 
>  >15m

**Comment by tens0rfl0w** [comment]
Number of active installations/clients may be possible to track remotely (server sided) when looking on the requests made to the distribution service. **But** this statistic can get completely inaccurate if someone decides to send some random requests to the distribution service for whatever reason. (IP logging is prohibited, so no way of tracking a single client)

Getting client statistics about the Exposure with other users/devices is also not possible in a accurate way,  because you don't know how many identifiers/keys in our local DB are from one singe device/user, so you cannot track the number of different user. Only thing you can do is to get the total number of keys saved on your device, but that is not a really usable measurement.

**Comment by AndreasIsenmann** [comment]
At least it would motivate to see that App is working if user can see how many contacts were registrated.

**Comment by tens0rfl0w** [comment]
@AndreasIsenmann Please see my comment for the reason this is not possible!

**Comment by hblaschka** [comment]
@tens0rfl0w - so this must be requested upstream at Google / Apple in order to be implementable, if I understand the API restrictions you described, right?

Is there a open channel between SAP and Apple regarding such discussions? 

The best argument I read regarding these statistical topics, of which a lot popped up so far, was that „users without technical expertise would like to be able to see that the app fulfills its purpose. Then they will be ready to recommend it to others.“

See:
https://github.com/corona-warn-app/cwa-wishlist/issues/5#issuecomment-646842549

**Comment by tens0rfl0w** [comment]
@hblaschka Yes, correct, there has to be vendor support, so Apple & Google are your partners for finding a solution for this problem. As unsatisfying as this is, right now we can only check for Errors from the framework and trust that this is accurate.

**Comment by tkowark** [comment]
Thank you very much for the suggestion. As noted above, this is really not something that can be fixed by the CWA team, especially short term.

As I don't want any idea to get lost, just a quick question: Would you consider this similar/identical to corona-warn-app/cwa-wishlist#5 or a different idea? In the first case, I would close this issue and concentrate discussions on the wishlist item. Of there are major differences, we can also move it to become a separate wishlist item.

**Comment by daimpi** [comment]
But even if Google/Apple allowed the app permanent access to the recorded data, a precise metric on how many contacts the phone had could not be obtained afaik: the app could have a statistic on the number of collected unique RPIs in this case, but the RPIs of each phone change every 10-15 min. So if the app knew that 100 RPIs were recorded in the last hour this could mean contact has been recorded with anywhere between ~17 - 100 different phones.

**Comment by hblaschka** [comment]
> As I don't want any idea to get lost, just a quick question: Would you consider this similar/identical to [corona-warn-app/cwa-wishlist#5](https://github.com/corona-warn-app/cwa-wishlist/issues/5) or a different idea?

As it is basically the same merge it - also merge the other similar feature requests / proposals. The overall argument really is: Is the app working or not - ATM users do not see any changes or action and this might make some uncomfortable.
