### ISSUE TITLE
App cannot be installed by certain 16 year olds

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-app-ios#690]
As discussed in #632, due to the age requirement in the app store being set to 17+, certain 16y olds, who have age restrictions on their device, cannot download the app.

This is a bug. It's unwanted behaviour.

The reasons given by @mynchau for closing are weak and were not properly discussed.
Since the Play store age requirement is 0+, legal requirements, as claimed, cannot be the reason for the need to set the age requirement to 17+.

Should be of interest to at least @an3k @Christian-Hemker @jdslab @thomasaugsten @jlnprssnr @fpientka

**Comment by jdslab** [comment]
The way I understand it is: iOS age restrictions are set on device, and installation of 17+ apps can be explicitly allowed in iOS Settings in _Screen Time -> Content & Privacy Restrictions -> Content Restrictions -> Apps_. This can also be done temporarily, just for downloading this single app. Could be at least a workaround.

**Comment by corneliusroemer** [comment]
Thanks for your comment @jdslab. A workaround doesn't fix the underlying root cause though, which is the setting 17+. The reasoning from maintainers for closing #632 was very weak in my opinion.

**Comment by fpientka** [comment]
I think it is fair to use 12+ (as WhatsApp does) because there are no GPDR data used. Even if iOS age restrictions is deactivated for installation of 17+ apps, it disappears and is unusable if activated again

**Comment by jlnprssnr** [comment]
@jdslab as mentioned by me before, this age restiction prohibilts people that are 16 years old from downloading the app. https://apps.apple.com/sa/story/id1440847896 It's not just a preference on the phone.

**Comment by corneliusroemer** [comment]
> @jdslab as mentioned by me before, this age restiction prohibilts people that are 16 years old from downloading the app. https://apps.apple.com/de/story/id1440847896 It's not just a preference on the phone.

This is what the description from Apple looks like. Sounds like Corona-Warn-App is a Sex or Drug app... And it says in bold you MUST be 17+

So this clearly underlines how this choice of age is highly misleading and harmful.

<img width="551" alt="Screenshot 2020-06-17 at 21 23 31" src="https://user-images.githubusercontent.com/25161793/84940900-d8855100-b0e0-11ea-942a-ac16f0c37d57.png">

**Comment by jdslab** [comment]
> @jdslab as mentioned by me before, this age restiction prohibilts people that are 16 years old from downloading the app. https://apps.apple.com/de/story/id1440847896 It's not just a preference on the phone.

I see, never mind then

**Comment by an3k** [comment]
As I wrote in the other issue: Just set it to "0 years" because

1. The Apple App Store age restriction settings has no legal meaning in Germany as they are ESRB ratings from the USA, _thus the SAP employees fear of breaking the law because of the DSGVO is non-existent._
2. The "17+" setting was made because of the DSGVO which requires you to be 16 years or older but the App itself has an integrated age check especially because of the DSGVO, _thus the Apple App Store age setting is not necessary._
3. The age setting in the Google Play Store was set to "0" because it uses the USK ratings. That however doesn't overwrites the DSGVO age restriction in any way so if 0 years is possible there, it is possible in the Apple App Store too.
4. People younger than 18 years cannot use the app if their parents enabled youth protection settings even if their parents give their permission because iOS prevents you from using this app (because it's rated "17+"). _Only choice for parents is to allow "17+" content or to completely disable youth protection settings. In both solutions would allow eg. 12 year olds to access content for 18 year olds just because of this app._

If you understand German you can read it here https://github.com/corona-warn-app/cwa-app-ios/issues/632#issuecomment-645605146

**Comment by mynchau** [comment]
Dear corneliusroemer, thanks for bringing up that issue. However, please understand that the representation in the app stores is the exclusive responsibility of the Robert Koch Institute. Please reach out to them at coronawarnapp@rki.de or via the other contact options listed on https://www.rki.de/EN/Service/Contact/Contact_node.html 
Since we are the wrong addressee we're closing this issue here.
Best regards
MC
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
Disclaimer: This is not a personal attack. I am stating my honest opinion as a member of the community that is advertised as a big part of this project.

I disagree with the way maintainers deal with this issue. To me it looks like deflecting responsibility.

You may be right that it's up to the RKI to change this. But this is not how you phrased it in the past.

Also, because this is a semi-technical issue, it is correct for it to be discussed here. You can say it is nothing that SAP/Telekom/maintainers can fix, but please do more about it by notifying RKI of this issue yourself.

I consider it a responsibility of contractors to inform the client of potential mistakes they are making.

Can you confirm that you have escalated this issue with RKI? There's a big difference between me writing as a lone citizen and a community-raised issue that has a community consensus.

I would like to invite community members @an3k @fpientka @jlnprssnr @jdslab to comment with their thoughts.

**Comment by Christian-Hemker** [comment]
@mynchau 
Dear Mynyna Chau,
thanks for your detailed answer. I understand that this setting in the App Store is not under your control, as you are not responsible for that.
However, the classification of the age limit seems to be based on the classification of medical treatment information. Because under the age specification 17+ the description: "Frequently/strongly pronounced: medical/treatment information" is listed. 
![IMG_7959](https://user-images.githubusercontent.com/1321477/85041324-11c5cb80-b18a-11ea-9039-42641083c04b.jpg)

You have advised us to contact the RKI directly. But there is no direct communication possibility there, as here in the Open Source Project. You have a direct line to the RKI and can communicate this suggestion much more easily so that it arrives at the right place.

Thanks for your time.

**Comment by corneliusroemer** [comment]
Further to @Christian-Hemker's point about us not having a direct link to the RKI:
I called the technical hotline to report the playstore country issue as well as this issue here. I was told they are aware but cannot say anything about it - they haven't received information from the RKI. I asked them to escalate, but they weren't very convinced that would change anything. I was told over 50% of calls in the past few days had been related to the app store issue. Yet we're still waiting for any updates there. Calling doesn't help, writing doesn't help. So it's natural the community feels let down a bit by maintainers.

So, just speaking to someone on a hotline doesn't work. It personally feels a bit like an insult for the app maintainers to tell us in the community to go down weird routes to raise awareness of an obvious issue for which there is community consensus.

**Comment by melloskitten** [comment]
Hi everybody, 

Thanks for your concerns & for submitting the issue. As I do not have family sharing enabled, and I haven't worked with it before, I would like to ask you a question - does the workaround mentioned by @jdslab work? Does it enable 'minors' to be able to use the CWA as well?

Thanks for checking! Here the comment again:

> The way I understand it is: iOS age restrictions are set on device, and installation of 17+ apps can be explicitly allowed in iOS Settings in _Screen Time -> Content & Privacy Restrictions -> Content Restrictions -> Apps_. This can also be done temporarily, just for downloading this single app. Could be at least a workaround.
