### ISSUE TITLE
Apple Watch App

### ISSUE THREAD

**Issue by peerst** [corona-warn-app/cwa-app-ios#709]
## Avoid duplicates
* [x] This issue has not already been raised before

## Current Implementation

No App on Apple Watch

## Suggested Enhancement

Have a App on Apple Watch which runs the Covid-19 protocol.  

## Expected Benefits

For many users the watch is always close by but iPhone is not (e.g. large iPhone models which don't fit in pockets).  Or e.g. some employers forbid having a phone at the workplace (seen in some shops where employees are quite exposed but are disallowed to have a phone with them)

**Comment by tens0rfl0w** [comment]
This is currently not possible, because the used framework for the contact tracing („Exposure Notification“) is only available on iOS an iPadOS devices. If you think this is a needed addition you should address this idea to Apple/Google.

But I agree, a watchOS application would be great!👍🏽
(But there is currently no indication from any vendor that this will happen, so it is very unlikely.)

See the [FAQ](https://www.coronawarn.app/en/faq/#smartwatch) for an official answer!

**Comment by peerst** [comment]
Why close this?

**Comment by haosap** [comment]
Hi @peerst ,
As @tens0rfl0w said, at the moment, the OS (watchOS) doesn't support it. As a Vendor, we cannot influent at the moment. If OS supports it, we will reopen it. Thanks.
