### ISSUE TITLE
Coroma-Warn-App überprüft das Protokoll der erfassten IDs nicht

### ISSUE THREAD

**Issue by JoachimSeuling** [corona-warn-app/cwa-app-ios#744]
Ich habe im COVID-19-Kontaktprotokoll auf meinem iPhone X, IOS 13.5.1. folgende Meldung:
„“Corona-Warn“ hat dein Protokoll mit erfassten zufälligen IDs während der letzten 24 Stunden 0-mal überprüft.“
Bei der Option „Kontaktüberprüfungen“ - „Dies ist eine Aufzeichnung aller Anfragen, dein Kontaktprotokoll der letzten 14 Tage zu überprüfen - erhalte ich die Meldung: 
„Dein Kontaktprotokoll wurde in den letzten 14 Tagen nicht überprüft.“
Ich habe die App seit 6 Tagen aktiv und war mehrfach in der Stadt unterwegs, auch im Café. Weiterhin hat im Haushalt ein weiteres Mitglied des Haushalts ein iPhone und die App ebenfalls aktiv. 
Sollte dann nicht zumindest der Abgleich zwischen diesen beiden Geräten sichtbar sein?

## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by inf2381** [comment]
The threshold for minimum amount of submitted key for a day package has not been reached yet. Hence, there is no package on the server available yet and the app didn't perform a detection session. But don't mix up the exposure detection with what the contact tracing. Your app is collecting contacts since you enabled it during the onboarding process. It just didn't check, whether some of your contacts have submitted themselves as positive Covid-19 cases.

Also. Please check the already closed issues the next time you submit a new issue. This is a duplicate of #311 and #721
