### ISSUE TITLE
Old data is being fetched again

### ISSUE THREAD

**Issue by felixoi** [corona-warn-app/cwa-app-ios#778]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

I recognized the app fetched two data sets this morning:
<img src="https://i.imgur.com/33cDk2E.png" width="200">
Then I took a look at the details and recognized following:
<img src="https://i.imgur.com/CBpTwq6.png" width="200">
<img src="https://i.imgur.com/gVAuh7i.png" width="200">
These are really two different sets of data. And the first one is identical  to the one of the day before:
<img src="https://i.imgur.com/ZKVhpo9.png" width="200">
So the app fetched old data again first.

## Expected behaviour

1. The app fetched two data sets on the same day. If I understood this correctly, it should only update once in 24 hours and therefore also only fetch one data set every 24 hours.
2. The app should not fetch old data again.

If these assumptions are wrong, I'm sorry and I did not fully understand how this should work.

## Steps to reproduce the issue

Not sure how to reproduce this.

## Technical details

- iOS Version: 13.5.1
- Device: iPhone XS Max

## Possible Fix

Not familiar enough with how the app works to answer this one.

**Comment by tens0rfl0w** [comment]
Can confirm this behavior. No errors.

**Comment by inf2381** [comment]
This is the intended behavior. Yesterday, the first day package from the server became available. That's why you see only one entry from yesterday. Today, the second package became available. Every 24 hours, the app feeds all available day packages from the last 14 days into the Exposure Notification framework because we need to calculate the overall risk from all keys that have been submitted within the relevant timeframe.

**Comment by tkowark** [comment]
And we now have added this to the FAQ, as well: https://www.coronawarn.app/en/faq/#multiple_exposure_checks
