### ISSUE TITLE
Misleading activate status

### ISSUE THREAD

**Issue by MaLub** [corona-warn-app/cwa-app-ios#784]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug
App shows me to activate ‚Risikoermittlung‘ but it‘s already activated. 

## Expected behaviour
‚Risikoermittlung‘ active

## Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/23558497/85828216-299fdf80-b788-11ea-9374-357e00419013.png)
![image](https://user-images.githubusercontent.com/23558497/85828280-4d632580-b788-11ea-88de-1aca94b7876d.png)
![image](https://user-images.githubusercontent.com/23558497/85828298-5653f700-b788-11ea-83f5-31459fa30700.png)

## Technical details

- iOS Version: 13.5.1
- Device: 11pro

**Comment by PITZH** [comment]
This issue came up in my app along with the issue "ENErrorDomain-Fehler 5 #766" one day after the first problem.

**Comment by aschafu** [comment]
My son has the same problem (see https://twitter.com/DiamondCoding/status/1275020318713819136) -- Started a few days ago and hasn't changed since. 
iPhone11pro, installed App first day, updated regularly, didn't deactivate App
My other son and I with identical iPhones don't have that problem.
Anything to do to debug?

**Comment by aschafu** [comment]
Another update: 
Might be related to  
[Risiko-Ermittlung nicht möglich #722](https://github.com/corona-warn-app/cwa-app-ios/issues/722). My son tapped on the text field above the button "Risikoermittlung einschalten", the dialogue that appeared allowed him to update and now everything seems to be fine. -- So maybe it's just the UI that's somehow broken / not logical.

**Comment by embeddedc** [comment]
![Corona](https://user-images.githubusercontent.com/4259379/86571662-1227da00-bf72-11ea-9454-49326e69b3b5.gif)

**Comment by jonasreiher** [comment]
For me the reason for this was deactivated **Background App Refresh (Hintergrundaktualisierungen)** in the iOS settings _(settings → general → background app refresh)_.
Activating this for the CWA immediately fixed things.

I think the app should check for this preference and encourage users to activate it. Otherwise the active status is indeed misleading. It lead me to reinstall it, which of course didn't help.

**Comment by MaLub** [comment]
> Another update: 
> 
> Might be related to  
> 
> [Risiko-Ermittlung nicht möglich #722](https://github.com/corona-warn-app/cwa-app-ios/issues/722). My son tapped on the text field above the button "Risikoermittlung einschalten", the dialogue that appeared allowed him to update and now everything seems to be fine. -- So maybe it's just the UI that's somehow broken / not logical. 
> 
> 

Yes, this solved my issue. Thank you. 
I‘ve called also the support: they told me to uninstall, reset etc the App, but this was nonsense

It‘s a broken UI and has to be solved :)

The background hint may also be worked - but I don‘t allow this to all the apps and in battery save mode this won‘t work either

**Comment by embeddedc** [comment]
> For me the reason for this was deactivated **Background App Refresh (Hintergrundaktualisierungen)** in the iOS settings _(settings → general → background app refresh)_.
> I think the app should check for this preference and encourage users to activate it.

Manual refresh worked fine with _Background App Refresh_ deactivated in the past. I do not see any reason why the Corona App should enforce this setting!?

**Comment by tkowark** [comment]
This should be fixed in the meantime. Especially in version 1.2., there will be a timer informing users about the remaining time until a new refresh can be triggered if background app refresh is deactivated. If background app refresh is activated, this state should never be reached but gone after 24h hours. If the problem persists with current versions, please open another issue.
