### ISSUE TITLE
App icon looks weird in contrast to other icons

### ISSUE THREAD

**Issue by moritzebeling** [corona-warn-app/cwa-app-ios#798]
When I look at the home screen of my phone, most apps icons have a sophisticated shape and bright colors. In contrast to them, the app icon of the CWA sticks out immediately. But not in good way. It looks a little sad, pale, maybe ill?
Also the C shape doesn’t look perfectly centered in the white tile.

Since we’re all having this app on our home screens for the months to come, I think, instead of being a little bit sad to look at, it should be beautiful instead.

I also started a general [redesign suggestion](https://github.com/corona-warn-app/cwa-wishlist/issues/78) as an issue in the wishlist repo.

![IMG_3112](https://user-images.githubusercontent.com/39742729/85990158-df219b80-b9f1-11ea-9bf5-94c0bf2676c9.png)

**Comment by tkowark** [comment]
Thanks @moritzebeling for being concerned about the well being of the poor CWA logo 😄 

As we already have the wishlist item, a separate issue in the app repos is not necessary and the logo would also be the same for both apps, anyways. Therefore, I'll close this issue here and refer everybody back to corona-warn-app/cwa-wishlist#78
