### ISSUE TITLE
Native Apple Watch Support.

### ISSUE THREAD

**Issue by NosDE** [corona-warn-app/cwa-app-ios#816]
Can you provide this App as an native App for the Apple Watch? 
As an Apple Watch (with LTE)  owner i leave my iPhone in some cases at home, because most things can be done by the Watch.
I think the watch as an additional supported device by the App would be great, because I wear always my watch.

**Comment by inf2381** [comment]
Please use our issue templates. If you choose enhancement, that template contains a link to the FAQ where this question has already been answered. But since this here is a feature request, that template would forward you to the [cwa-wishlist](https://github.com/corona-warn-app/cwa-wishlist/issues) repository where this has also been posted before. See [12](https://github.com/corona-warn-app/cwa-wishlist/issues/12)
