### ISSUE TITLE
Battery usage increased since some days

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#912]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Since some days (more than 14 days since installing the app) I am seeing an increased battery usage from the Health COVID-19 Contact Protocol. In this issue here, I´m not talking about the general/constant battery usage, but of an **increased** usage after an initial period. Therefore, I´m opening a new issue, because I see this change in behavior as a seperate topic.

After the first 10 days of app usage, I saw 5% battery usage by the Contact Protocol (10 day average). But since some days, this increased significantly, and the 10 day average doubled to 10%.

I know, that this problably doesn´t have to do directly with the app, but can you please take this up to check with Apple?
I thought of reasons, why the battery usage could increase after an initial constant usage. I had the idea, that the more IDs the device is collecting over time, the more IDs it has to process and broadcast. So, in theory, the local processing of IDs and broadcasting via BT could consume more energy.

Can you validate if this makes sense or if there is another reason? And how this could be optimized.

## Expected behaviour

Constant battery usage during the whole time using the app.

## Steps to reproduce the issue

Install app initially (or initialize app), and monitor the battery usage of the contact protocol over a period of more than 14 days.

## Technical details

- iOS Version: 13.5.1
- Device: iPhone Xs

## Additional context

I dont´t have screenshots of the first 10 days anymore, but here are current screenshots from today:

![IMG_1147](https://user-images.githubusercontent.com/36116339/87583396-29866600-c6dc-11ea-82bc-8c41f21fed38.PNG)

![IMG_1146](https://user-images.githubusercontent.com/36116339/87583406-2f7c4700-c6dc-11ea-848b-6d65fea83256.PNG)

**Comment by Tho-Mat** [comment]
How do you know that.
You only see %-values. So % of what. 
The %-values are related to the overall usage.
If you tab on hours in the night you will see 100% usage of COVID-19 (or maybe 50 since you run OSTHESSEN new.)
For today, i have 55% for COVID-19.
On the day with most usage COVID-19 is only 10%.
So it would be better, if Apple would show the mAh. That would be the only way to check if the usage has changed.

**Comment by mss1010** [comment]
Ok thats true. But what I forgot to mention is, that the battery drained faster overall, while I was using the iPhone **less** than before. At least thats the case based on screen time in settings.

See the screenshots of the last few weeks, especially the daily average

![A935367F-B9F9-437D-9F35-BF4B6B3C5F12](https://user-images.githubusercontent.com/36116339/87635736-d8a85900-c73f-11ea-8137-462662b57f57.jpeg)

![3ECE242F-B26F-45AA-A66D-99043452D784](https://user-images.githubusercontent.com/36116339/87635754-df36d080-c73f-11ea-85cd-d8954cca3303.jpeg)

![69655637-1094-453D-8EB1-9ED0E2D4D15C](https://user-images.githubusercontent.com/36116339/87635764-e65dde80-c73f-11ea-994e-7b269f24b12f.jpeg)

**Comment by SebastianWolf-SAP** [comment]
Dear @mss1010,

a sudden increase of battery consumption was also reported in the already existing issue #671 - along with other battery-related issues. Let's collect all the battery-related topics in one issue. Otherwise, we lose oversight and may not be able to see correlations.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
