### ISSUE TITLE
Risiko-Ermittlung im Hintergrund nicht zuverlässig?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#920]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue
=> similar behaviour is reported on iOS 13.6 by other users, see issue #916 but I have iOS 13.5.1

## Describe the bug

Ich habe den Verdacht, daß bei mir die Risiko-Ermittlung (Download der Exposure Codes) im Hintergrund nicht zuverlässig funktioniert. Gibt es dazu Beobachtungen / Informationen / Empfehlungen?

Ich habe iPhone 8, iOS 13.5.1, Corona App Version 1.0.7(0).
Ich bin nachts im WLAN daheim, tagsüber im WLAN in der Firma, dazwischen bin ich bis zu 2 Std unterwegs ohne WLAN, mit unterschiedlich guter Netzabdeckung, auch Funklöcher, dh nicht durchgängig Internet.
Ich beobachte, daß die Zeitabstände zwischen der täglichen Risiko-Ermittlung deutlich > 24 Stunden sind, vor allem in der letzten Woche: Mo 13.07. 09:39 / Di 14.07. 10:04 / Mi 15.07. 10:36 / Do 16.07. 12:30 / Fr 17.07. 17:21 / Sa 18.07. 18:07
Vor allem in den letzten zwei Tagen war der Zeitpunkt exakt der, wo ich mein Handy eingeschaltet hatte.

Wie wird der Download der Exposure Codes angestossen? Vom Server (zB Push Notification), oder lokal (zB Timer)?
Was passiert, wenn ich in diesem Moment im Funkloch bin (also ohne Internet) - gibt es dann einen weiteren Versuch später?

Anmerkung: Beobachtung ähnlich wie #916, allerdings bei mir iOS 13.5.1

## Technical details

- iOS Version: 13.5.1
- Device: iPhone 8
- Corona app Version 1.0.7(0)

**Comment by SebastianWolf-SAP** [comment]
We also have a dedicated issue for the same issue with iOS 13.5(.1), see #740. This issue has already been under investigation for a while and we will provide an update as soon as possible.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Thanks @SebastianWolf-SAP for pointing me to #740 - very interesting discussion there; and, yes, it matches 100% with my observations.
Sorry for the duplicate, I was not aware of that other ticket.

**Comment by databus23** [comment]
@SebastianWolf-SAP I don't think this is necessarily about the same issue as reported in #740. In this issue the consensus seems to be this only happens after restarting the device and not starting the app at least once after the restart.
This is not what I'm observing for at least a week on iOS 13.5.1 where the background refresh does not work at all anymore on multiple devices. See my comment here: https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-660539895.

**Comment by SebastianWolf-SAP** [comment]
@databus23 Thanks for the comment. We also don't know yet if we are facing a single or multiple issues, if - in case of multiple issues - one is related to the iOS upgrade or if we have introduced a regression in the app with one of the latest releases. No matter what, it has been addressed with highest priority to development and they will have a look at it and analyze it in several scenarios.

But please understand that we won't leave more issues with the same symptom open beyond #740 and #916. Otherwise it might become slightly confusing for all of us...

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by databus23** [comment]
@SebastianWolf-SAP Ok thats fair. But maybe we can agree to remove the [13.6] prefix from #916 title? As my and other comments suggest this is already an issue with 13.5.1 and not covered by #740 which is about background task scheduling after a restart.

**Comment by SebastianWolf-SAP** [comment]
It's the current working assumption that the iOS upgrade somehow plays a role here - therefore we left #916 open. In case our dev team finds out that both issues belong together, we will rather close one (most certainly #916) and use #740 exclusively instead of renaming the titles.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by databus23** [comment]
@SebastianWolf-SAP Hmm, my main point is the background actualisation was flaky at best on 13.5.1 already. I have 4 phones in my family with huge gaps in the check history. In fact I have yet to find a phone where the background checks have worked reliable in the week before 13.6 even shipped. #740 is locked, no way to add information and from the flow of the conversation it seems like the consensus is that the problem is with apple and related to triggering background checks after a restart. This is not what I'm observing. The background checks do not work for all the phones I have access to. Even if the app has been started at least once. From my point focusing on 13.6 update could be a red herring as this clearly has been a problem before.

**Comment by SebastianWolf-SAP** [comment]
I can only underline what I wrote in https://github.com/corona-warn-app/cwa-app-ios/issues/920#issuecomment-660864262 - the issue is under investigation with an open end. #916 is there to add information which might lead to 13.6-specific conditions. If no further details come out, we also might need to lock it for further conversations as we did with #740. In #740 I just added a note referring to this issue and the required investigation.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by FabianKroenner** [comment]
Hello colleagues
After becoming aware of this issue, I checked my wife's iPhone today and can share my findings:
- the app was updated to version 1.1.1 yesterday, 22.07.2020
Then I looked into the "Exposure Checks" on her device:
- the oldest Entry in the log is from 04.07.2020
- daily updates from 04.-09.07.2020
- no updated between 09.07.2020 and 18.07.2020
- the last update on her phone happened on 18.07.2020
I can rule out that the iPhone was updated to 13.6 before release, so essentially the issue appeared on 10 July on iOS 13.5.1
Best Regards
