### ISSUE TITLE
UI: "Anzahl der bereitgestellten Schlüssel" is clipped

### ISSUE THREAD

**Issue by dbcb** [corona-warn-app/cwa-app-ios#998]
Hi all,
I have increased the text size of my iPhoneX for better reading.
In "settings->Corona-Warn->Covid-19-Kontaktprotokoll"->Kontaktverknüfung-><date>" the text
is too long for the UI and is clipped.  
I only see:

* Anzahl der bereitgestellten Schlu...
* Anzahl der abgeglichenen Schlü...

Maybe this is an iOS problem, but it would be better to use 2 lines for this.

The Text is also very unclear and suggest that the corona warn app doesn't work.
A user can interpret "Anzahl der abgeglichenen Schlüssel" as Keys, that the smartphone has
retrieved and checked. Though zero is interpreted as "app didn't work".
For The developer this is clear. For the user it is confusing.

I suggest the following:

- Anzahl der bereitgestellten Schlüssel -> Anzahl bekannter Infektionen
- Anzahl der abgeglichenen Schlüssel -> Kontakt zu bekannten Infektionen

Example:

Anzahl bekannter Infektionen: 2135
Kontakt zu bekannten Infektionen: 0

My definition is also not perfect but for me better understandable

Is is extremly important that there is no doubt that the corona warn app is working

**Comment by GPclips** [comment]
Hello @dbcb ,

as mentioned by @sin-azucar, this happens due to iOS and should be addressd to apple.
Also for a better understanding of the keys and the general functionality, please read through this article: https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

Thanks,

LMM

Corona-Warn-App Open Source Team
